import ROOT, re
from math import *
execfile("/home/jpivarski/bin/tdrstyle.py")
tdrStyle.SetOptTitle(1)
tdrStyle.SetTitleBorderSize(1)
# tdrStyle.SetFillColor(ROOT.kWhite)
tdrStyle.SetTitleFontSize(0.1)
c1 = ROOT.TCanvas()
fakename = None
plotDirectory = "MuonAlignmentFromReference"

ROOT.gROOT.ProcessLine(".x fitfunc.C")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter01_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter04.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter04_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE/DTCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE/DTCRAFTiter01_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE/DTCRAFTiter04.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE/DTCRAFTiter04_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE/CSCCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE/CSCCRAFTiter01_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_optimal/DTCRAFTiter04.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_optimal/DTCRAFTiter04_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_afterFinal/DTCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_afterFinal/DTCRAFTiter01_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_100GeV/DTCRAFTiter03.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_100GeV/DTCRAFTiter03_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_100GeV_afterFixErrors/DTCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_wAPE_100GeV_afterFixErrors/DTCRAFTiter01_report.py")

# nan = 10000.
# inf = 10000.
# # all of the inf/nans are in DT 1, 2, 7 errors
# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter01_report.py")

# # no inf/nans
# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter02.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter02_report.py")

# # no inf/nans
# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter03.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter03_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter04.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter04_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter05.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT_wAPE_100GeV_newinternal/DTCRAFTiter05_report.py")

execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1_realtracker_Millepede/DTCRAFTMPiter01_report.py")

tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1/DTCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1/DTCRAFTiter01_report.py")

tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1/DTCRAFTiter03.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1/DTCRAFTiter03_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTMC1_sync1/DTMCiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTMC1_sync1/DTMCiter01_report.py")

tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTMC1_sync1/DTMCiter03.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/DTMC1_sync1/DTMCiter03_report.py")

tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/DTCRAFT1_sync1_realtracker_Millepede/DTCRAFTMPiter01.root")

# ####

# # iter01: "CSChardwareAndPG.db"
# # iter02: "CSCphotogrammetry.db"
# # iter03: "V11alignment.db"
# # iter04: "idealAlignment.db"

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter01.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter01_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter02.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter02_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter03.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter03_report.py")

# tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter04.root")
# execfile("/home/jpivarski/work/results/CRAFTchambers2/CSCCRAFT1_wAPE_restricted/CSCCRAFTiter04_report.py")

# # tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/geometryonly_dt.root")
# # plotDirectory = "TestIt"
# # execfile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter01_report.py")
# # reports = [Report(12345, ("DT", -2, 1, 1), "DTexample")]
# # reports[-1].status = "PASS"
# # fakename = "DT geometry only"

# # tfile = ROOT.TFile("/home/jpivarski/work/results/CRAFTchambers2/geometryonly_csc.root")
# # plotDirectory = "TestIt"
# # execfile("/home/jpivarski/work/results/CRAFTchambers2/ALLATONCE_PATTERN4/PATTERNiter01_report.py")
# # reports = [Report(12345, ("CSC", 1, 1, 1, 1), "CSCexample")]
# # reports[-1].status = "PASS"
# # fakename = "CSC geometry only"

def getname(r):
    if fakename is not None: return fakename
    if r.postal_address[0] == "DT":
        wheel, station, sector = r.postal_address[1:]
        return "DT wheel %d, station %d, sector %d" % (wheel, station, sector)
    elif r.postal_address[0] == "CSC":
        endcap, station, ring, chamber = r.postal_address[1:]
        if endcap != 1: station = -1 * abs(station)
        return "CSC ME%d/%d chamber %d" % (station, ring, chamber)

def bellcurves(name, twobin=True, suppressblue=False):
    found = False
    for r in reports:
        if r.name == name:
            found = True
            break
    if not found: raise Exception, "Not a valid name"
    if r.status == "FAIL": raise Exception, "Fit failed"
    
    Pos = "Pos"; Neg = "Neg"
    if not twobin:
        Pos = ""; Neg = ""

    chamber_x = tfile.Get("%s/%s%s_x" % (plotDirectory, name, Pos))
    chamber_x_fit = tfile.Get("%s/%s%s_x_fit" % (plotDirectory, name, Pos))
    chamber_y = tfile.Get("%s/%s%s_y" % (plotDirectory, name, Pos))
    chamber_y_fit = tfile.Get("%s/%s%s_y_fit" % (plotDirectory, name, Pos))
    chamber_dxdz = tfile.Get("%s/%s%s_dxdz" % (plotDirectory, name, Pos))
    chamber_dxdz_fit = tfile.Get("%s/%s%s_dxdz_fit" % (plotDirectory, name, Pos))
    chamber_dydz = tfile.Get("%s/%s%s_dydz" % (plotDirectory, name, Pos))
    chamber_dydz_fit = tfile.Get("%s/%s%s_dydz_fit" % (plotDirectory, name, Pos))
    chamber_alphax = tfile.Get("%s/%s%s_alphax" % (plotDirectory, name, Pos))
    chamber_alphax_fit = tfile.Get("%s/%s%s_alphax_fit" % (plotDirectory, name, Pos))
    chamber_alphay = tfile.Get("%s/%s%s_alphay" % (plotDirectory, name, Pos))
    chamber_alphay_fit = tfile.Get("%s/%s%s_alphay_fit" % (plotDirectory, name, Pos))
    chamber_x_fit2 = tfile.Get("%s/%s%s_x_fit" % (plotDirectory, name, Neg))
    chamber_y_fit2 = tfile.Get("%s/%s%s_y_fit" % (plotDirectory, name, Neg))
    chamber_dxdz_fit2 = tfile.Get("%s/%s%s_dxdz_fit" % (plotDirectory, name, Neg))
    chamber_dydz_fit2 = tfile.Get("%s/%s%s_dydz_fit" % (plotDirectory, name, Neg))
    chamber_alphax_fit2 = tfile.Get("%s/%s%s_alphax_fit" % (plotDirectory, name, Neg))
    chamber_alphay_fit2 = tfile.Get("%s/%s%s_alphay_fit" % (plotDirectory, name, Neg))

    if chamber_x is None:
        chamber_x = tfile.Get("%s/%s%s_residual" % (plotDirectory, name, Pos))
        chamber_x_fit = tfile.Get("%s/%s%s_residual_fit" % (plotDirectory, name, Pos))
        chamber_dxdz = tfile.Get("%s/%s%s_resslope" % (plotDirectory, name, Pos))
        chamber_dxdz_fit = tfile.Get("%s/%s%s_resslope_fit" % (plotDirectory, name, Pos))
        chamber_alphax = tfile.Get("%s/%s%s_alpha" % (plotDirectory, name, Pos))
        chamber_alphax_fit = tfile.Get("%s/%s%s_alpha_fit" % (plotDirectory, name, Pos))
        chamber_x_fit2 = tfile.Get("%s/%s%s_residual_fit" % (plotDirectory, name, Neg))
        chamber_dxdz_fit2 = tfile.Get("%s/%s%s_resslope_fit" % (plotDirectory, name, Neg))
        chamber_alphax_fit2 = tfile.Get("%s/%s%s_alpha_fit" % (plotDirectory, name, Neg))

    ####
    chamber_x.SetAxisRange(-30., 30., "X")
    chamber_dxdz.SetAxisRange(-50., 50., "X")
    if chamber_y is not None:
        chamber_y.SetAxisRange(-50., 50., "X")
        chamber_dydz.SetAxisRange(-200., 200., "X")
    ####

    chamber_x.SetXTitle("Local x residual (mm)")
    chamber_dxdz.SetXTitle("Local dx/dz residual (mrad)")
    chamber_alphax.SetXTitle("Local dx/dz residual (mrad)")
    chamber_alphax.SetYTitle("Local x residual (mm)")
    if chamber_y is not None:
        chamber_y.SetXTitle("Local y residual (mm)")
        chamber_dydz.SetXTitle("Local dy/dz residual (mrad)")
        chamber_alphay.SetXTitle("Local dy/dz residual (mrad)")
        chamber_alphay.SetYTitle("Local y residual (mm)")
    if name[0:2] == "ME":
        chamber_x.SetXTitle("Local r#phi residual (mm)")
        chamber_dxdz.SetXTitle("Local d(r#phi)/dz residual (mrad)")
        chamber_alphax.SetXTitle("Local d(r#phi)/dz residual (mrad)")
        chamber_alphax.SetYTitle("Local r#phi residual (mm)")

    for h in chamber_x, chamber_dxdz, chamber_alphax, chamber_alphax, chamber_y, chamber_dydz, chamber_alphay, chamber_alphay:
        if h is not None:
            h.GetXaxis().CenterTitle()
            h.GetYaxis().CenterTitle()
            h.GetXaxis().SetLabelSize(0.05)
            h.GetYaxis().SetLabelSize(0.05)
            h.GetXaxis().SetTitleSize(0.07)
            h.GetYaxis().SetTitleSize(0.07)
            h.GetXaxis().SetTitleOffset(0.9)
            h.GetYaxis().SetTitleOffset(0.9)

    for f in chamber_x_fit2, chamber_y_fit2, chamber_dxdz_fit2, chamber_dydz_fit2, chamber_alphax_fit2, chamber_alphay_fit2:
        if f is not None:
            f.SetLineColor(4)

    if chamber_y is not None:
        c1.Clear()
        c1.Divide(3, 2)
        chamber_x.SetTitle(getname(r))
        c1.GetPad(1).cd(); chamber_x.Draw(); (None if suppressblue else chamber_x_fit2.Draw("same")); chamber_x_fit.Draw("same")
        c1.GetPad(2).cd(); chamber_dxdz.Draw(); (None if suppressblue else chamber_dxdz_fit2.Draw("same")); chamber_dxdz_fit.Draw("same")
        c1.GetPad(3).cd(); chamber_alphax.Draw(); (None if suppressblue else chamber_alphax_fit2.Draw("same")); chamber_alphax_fit.Draw("same")
        c1.GetPad(4).cd(); chamber_y.Draw(); (None if suppressblue else chamber_y_fit2.Draw("same")); chamber_y_fit.Draw("same")
        c1.GetPad(5).cd(); chamber_dydz.Draw(); (None if suppressblue else chamber_dydz_fit2.Draw("same")); chamber_dydz_fit.Draw("same")
        c1.GetPad(6).cd(); chamber_alphay.Draw(); (None if suppressblue else chamber_alphay_fit2.Draw("same")); chamber_alphay_fit.Draw("same")

    else:
        c1.Clear()
        c1.Divide(3, 1)
        chamber_x.SetTitle(getname(r))
        c1.GetPad(1).cd(); chamber_x.Draw(); (None if suppressblue else chamber_x_fit2.Draw("same")); chamber_x_fit.Draw("same")
        c1.GetPad(2).cd(); chamber_dxdz.Draw(); (None if suppressblue else chamber_dxdz_fit2.Draw("same")); chamber_dxdz_fit.Draw("same")
        c1.GetPad(3).cd(); chamber_alphax.Draw(); (None if suppressblue else chamber_alphax_fit2.Draw("same")); chamber_alphax_fit.Draw("same")

#    c1.SaveAs("tmpbell_%s.pdf" % name)

def polynomials(name, twobin=True, suppressblue=False):
    global label1, label2, label3, label4, label5, label6, label7, label8, label9

    found = False
    for r in reports:
        if r.name == name:
            found = True
            break
    if not found: raise Exception, "Not a valid name"
    if r.status == "FAIL": raise Exception, "Fit failed"

    Pos = "Pos"; Neg = "Neg"
    if not twobin:
        Pos = ""; Neg = ""

    chamber_x_trackx = tfile.Get("%s/%s%s_x_trackx" % (plotDirectory, name, Pos))
    chamber_x_trackx_fit = tfile.Get("%s/%s%s_x_trackx_fitline" % (plotDirectory, name, Pos))
    chamber_y_trackx = tfile.Get("%s/%s%s_y_trackx" % (plotDirectory, name, Pos))
    chamber_y_trackx_fit = tfile.Get("%s/%s%s_y_trackx_fitline" % (plotDirectory, name, Pos))
    chamber_dxdz_trackx = tfile.Get("%s/%s%s_dxdz_trackx" % (plotDirectory, name, Pos))
    chamber_dxdz_trackx_fit = tfile.Get("%s/%s%s_dxdz_trackx_fitline" % (plotDirectory, name, Pos))
    chamber_dydz_trackx = tfile.Get("%s/%s%s_dydz_trackx" % (plotDirectory, name, Pos))
    chamber_dydz_trackx_fit = tfile.Get("%s/%s%s_dydz_trackx_fitline" % (plotDirectory, name, Pos))
    chamber_x_trackx_fit2 = tfile.Get("%s/%s%s_x_trackx_fitline" % (plotDirectory, name, Neg))
    chamber_y_trackx_fit2 = tfile.Get("%s/%s%s_y_trackx_fitline" % (plotDirectory, name, Neg))
    chamber_dxdz_trackx_fit2 = tfile.Get("%s/%s%s_dxdz_trackx_fitline" % (plotDirectory, name, Neg))
    chamber_dydz_trackx_fit2 = tfile.Get("%s/%s%s_dydz_trackx_fitline" % (plotDirectory, name, Neg))

    chamber_x_tracky = tfile.Get("%s/%s%s_x_tracky" % (plotDirectory, name, Pos))
    chamber_x_tracky_fit = tfile.Get("%s/%s%s_x_tracky_fitline" % (plotDirectory, name, Pos))
    chamber_y_tracky = tfile.Get("%s/%s%s_y_tracky" % (plotDirectory, name, Pos))
    chamber_y_tracky_fit = tfile.Get("%s/%s%s_y_tracky_fitline" % (plotDirectory, name, Pos))
    chamber_dxdz_tracky = tfile.Get("%s/%s%s_dxdz_tracky" % (plotDirectory, name, Pos))
    chamber_dxdz_tracky_fit = tfile.Get("%s/%s%s_dxdz_tracky_fitline" % (plotDirectory, name, Pos))
    chamber_dydz_tracky = tfile.Get("%s/%s%s_dydz_tracky" % (plotDirectory, name, Pos))
    chamber_dydz_tracky_fit = tfile.Get("%s/%s%s_dydz_tracky_fitline" % (plotDirectory, name, Pos))
    chamber_x_tracky_fit2 = tfile.Get("%s/%s%s_x_tracky_fitline" % (plotDirectory, name, Neg))
    chamber_y_tracky_fit2 = tfile.Get("%s/%s%s_y_tracky_fitline" % (plotDirectory, name, Neg))
    chamber_dxdz_tracky_fit2 = tfile.Get("%s/%s%s_dxdz_tracky_fitline" % (plotDirectory, name, Neg))
    chamber_dydz_tracky_fit2 = tfile.Get("%s/%s%s_dydz_tracky_fitline" % (plotDirectory, name, Neg))

    chamber_x_trackdxdz = tfile.Get("%s/%s%s_x_trackdxdz" % (plotDirectory, name, Pos))
    chamber_x_trackdxdz_fit = tfile.Get("%s/%s%s_x_trackdxdz_fitline" % (plotDirectory, name, Pos))
    chamber_y_trackdxdz = tfile.Get("%s/%s%s_y_trackdxdz" % (plotDirectory, name, Pos))
    chamber_y_trackdxdz_fit = tfile.Get("%s/%s%s_y_trackdxdz_fitline" % (plotDirectory, name, Pos))
    chamber_dxdz_trackdxdz = tfile.Get("%s/%s%s_dxdz_trackdxdz" % (plotDirectory, name, Pos))
    chamber_dxdz_trackdxdz_fit = tfile.Get("%s/%s%s_dxdz_trackdxdz_fitline" % (plotDirectory, name, Pos))
    chamber_dydz_trackdxdz = tfile.Get("%s/%s%s_dydz_trackdxdz" % (plotDirectory, name, Pos))
    chamber_dydz_trackdxdz_fit = tfile.Get("%s/%s%s_dydz_trackdxdz_fitline" % (plotDirectory, name, Pos))
    chamber_x_trackdxdz_fit2 = tfile.Get("%s/%s%s_x_trackdxdz_fitline" % (plotDirectory, name, Neg))
    chamber_y_trackdxdz_fit2 = tfile.Get("%s/%s%s_y_trackdxdz_fitline" % (plotDirectory, name, Neg))
    chamber_dxdz_trackdxdz_fit2 = tfile.Get("%s/%s%s_dxdz_trackdxdz_fitline" % (plotDirectory, name, Neg))
    chamber_dydz_trackdxdz_fit2 = tfile.Get("%s/%s%s_dydz_trackdxdz_fitline" % (plotDirectory, name, Neg))

    chamber_x_trackdydz = tfile.Get("%s/%s%s_x_trackdydz" % (plotDirectory, name, Pos))
    chamber_x_trackdydz_fit = tfile.Get("%s/%s%s_x_trackdydz_fitline" % (plotDirectory, name, Pos))
    chamber_y_trackdydz = tfile.Get("%s/%s%s_y_trackdydz" % (plotDirectory, name, Pos))
    chamber_y_trackdydz_fit = tfile.Get("%s/%s%s_y_trackdydz_fitline" % (plotDirectory, name, Pos))
    chamber_dxdz_trackdydz = tfile.Get("%s/%s%s_dxdz_trackdydz" % (plotDirectory, name, Pos))
    chamber_dxdz_trackdydz_fit = tfile.Get("%s/%s%s_dxdz_trackdydz_fitline" % (plotDirectory, name, Pos))
    chamber_dydz_trackdydz = tfile.Get("%s/%s%s_dydz_trackdydz" % (plotDirectory, name, Pos))
    chamber_dydz_trackdydz_fit = tfile.Get("%s/%s%s_dydz_trackdydz_fitline" % (plotDirectory, name, Pos))
    chamber_x_trackdydz_fit2 = tfile.Get("%s/%s%s_x_trackdydz_fitline" % (plotDirectory, name, Neg))
    chamber_y_trackdydz_fit2 = tfile.Get("%s/%s%s_y_trackdydz_fitline" % (plotDirectory, name, Neg))
    chamber_dxdz_trackdydz_fit2 = tfile.Get("%s/%s%s_dxdz_trackdydz_fitline" % (plotDirectory, name, Neg))
    chamber_dydz_trackdydz_fit2 = tfile.Get("%s/%s%s_dydz_trackdydz_fitline" % (plotDirectory, name, Neg))

    if chamber_x_trackx is None:
        chamber_x_trackx = tfile.Get("%s/%s%s_residual_trackx" % (plotDirectory, name, Pos))
        chamber_x_trackx_fit = tfile.Get("%s/%s%s_residual_trackx_fitline" % (plotDirectory, name, Pos))
        chamber_dxdz_trackx = tfile.Get("%s/%s%s_resslope_trackx" % (plotDirectory, name, Pos))
        chamber_dxdz_trackx_fit = tfile.Get("%s/%s%s_resslope_trackx_fitline" % (plotDirectory, name, Pos))
        chamber_x_trackx_fit2 = tfile.Get("%s/%s%s_residual_trackx_fitline" % (plotDirectory, name, Neg))
        chamber_dxdz_trackx_fit2 = tfile.Get("%s/%s%s_resslope_trackx_fitline" % (plotDirectory, name, Neg))

        chamber_x_tracky = tfile.Get("%s/%s%s_residual_tracky" % (plotDirectory, name, Pos))
        chamber_x_tracky_fit = tfile.Get("%s/%s%s_residual_tracky_fitline" % (plotDirectory, name, Pos))
        chamber_dxdz_tracky = tfile.Get("%s/%s%s_resslope_tracky" % (plotDirectory, name, Pos))
        chamber_dxdz_tracky_fit = tfile.Get("%s/%s%s_resslope_tracky_fitline" % (plotDirectory, name, Pos))
        chamber_x_tracky_fit2 = tfile.Get("%s/%s%s_residual_tracky_fitline" % (plotDirectory, name, Neg))
        chamber_dxdz_tracky_fit2 = tfile.Get("%s/%s%s_resslope_tracky_fitline" % (plotDirectory, name, Neg))

        chamber_x_trackdxdz = tfile.Get("%s/%s%s_residual_trackdxdz" % (plotDirectory, name, Pos))
        chamber_x_trackdxdz_fit = tfile.Get("%s/%s%s_residual_trackdxdz_fitline" % (plotDirectory, name, Pos))
        chamber_dxdz_trackdxdz = tfile.Get("%s/%s%s_resslope_trackdxdz" % (plotDirectory, name, Pos))
        chamber_dxdz_trackdxdz_fit = tfile.Get("%s/%s%s_resslope_trackdxdz_fitline" % (plotDirectory, name, Pos))
        chamber_x_trackdxdz_fit2 = tfile.Get("%s/%s%s_residual_trackdxdz_fitline" % (plotDirectory, name, Neg))
        chamber_dxdz_trackdxdz_fit2 = tfile.Get("%s/%s%s_resslope_trackdxdz_fitline" % (plotDirectory, name, Neg))

        chamber_x_trackdydz = tfile.Get("%s/%s%s_residual_trackdydz" % (plotDirectory, name, Pos))
        chamber_x_trackdydz_fit = tfile.Get("%s/%s%s_residual_trackdydz_fitline" % (plotDirectory, name, Pos))
        chamber_dxdz_trackdydz = tfile.Get("%s/%s%s_resslope_trackdydz" % (plotDirectory, name, Pos))
        chamber_dxdz_trackdydz_fit = tfile.Get("%s/%s%s_resslope_trackdydz_fitline" % (plotDirectory, name, Pos))
        chamber_x_trackdydz_fit2 = tfile.Get("%s/%s%s_residual_trackdydz_fitline" % (plotDirectory, name, Neg))
        chamber_dxdz_trackdydz_fit2 = tfile.Get("%s/%s%s_resslope_trackdydz_fitline" % (plotDirectory, name, Neg))

    chamber_x_trackx = chamber_x_trackx.Clone()
    chamber_dxdz_trackx = chamber_dxdz_trackx.Clone()
    chamber_x_tracky = chamber_x_tracky.Clone()
    chamber_dxdz_tracky = chamber_dxdz_tracky.Clone()
    chamber_x_trackdxdz = chamber_x_trackdxdz.Clone()
    chamber_dxdz_trackdxdz = chamber_dxdz_trackdxdz.Clone()
    chamber_x_trackdydz = chamber_x_trackdydz.Clone()
    chamber_dxdz_trackdydz = chamber_dxdz_trackdydz.Clone()

    if chamber_y_trackx is not None:
        chamber_y_trackx = chamber_y_trackx.Clone()
        chamber_dydz_trackx = chamber_dydz_trackx.Clone()
        chamber_y_tracky = chamber_y_tracky.Clone()
        chamber_dydz_tracky = chamber_dydz_tracky.Clone()
        chamber_y_trackdxdz = chamber_y_trackdxdz.Clone()
        chamber_dydz_trackdxdz = chamber_dydz_trackdxdz.Clone()
        chamber_y_trackdydz = chamber_y_trackdydz.Clone()
        chamber_dydz_trackdydz = chamber_dydz_trackdydz.Clone()

    if chamber_y_trackx is not None:
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_x_trackx" % (plotDirectory, name, Neg))); chamber_x_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dxdz_trackx" % (plotDirectory, name, Neg))); chamber_dxdz_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_x_tracky" % (plotDirectory, name, Neg))); chamber_x_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dxdz_tracky" % (plotDirectory, name, Neg))); chamber_dxdz_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_x_trackdxdz" % (plotDirectory, name, Neg))); chamber_x_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dxdz_trackdxdz" % (plotDirectory, name, Neg))); chamber_dxdz_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_x_trackdydz" % (plotDirectory, name, Neg))); chamber_x_trackdydz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dxdz_trackdydz" % (plotDirectory, name, Neg))); chamber_dxdz_trackdydz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_y_trackx" % (plotDirectory, name, Neg))); chamber_y_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dydz_trackx" % (plotDirectory, name, Neg))); chamber_dydz_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_y_tracky" % (plotDirectory, name, Neg))); chamber_y_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dydz_tracky" % (plotDirectory, name, Neg))); chamber_dydz_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_y_trackdxdz" % (plotDirectory, name, Neg))); chamber_y_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dydz_trackdxdz" % (plotDirectory, name, Neg))); chamber_dydz_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_y_trackdydz" % (plotDirectory, name, Neg))); chamber_y_trackdydz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_dydz_trackdydz" % (plotDirectory, name, Neg))); chamber_dydz_trackdydz.Merge(tlist)
    else:
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_residual_trackx" % (plotDirectory, name, Neg))); chamber_x_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_resslope_trackx" % (plotDirectory, name, Neg))); chamber_dxdz_trackx.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_residual_tracky" % (plotDirectory, name, Neg))); chamber_x_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_resslope_tracky" % (plotDirectory, name, Neg))); chamber_dxdz_tracky.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_residual_trackdxdz" % (plotDirectory, name, Neg))); chamber_x_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_resslope_trackdxdz" % (plotDirectory, name, Neg))); chamber_dxdz_trackdxdz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_residual_trackdydz" % (plotDirectory, name, Neg))); chamber_x_trackdydz.Merge(tlist)
        tlist = ROOT.TList(); tlist.Add(tfile.Get("%s/%s%s_resslope_trackdydz" % (plotDirectory, name, Neg))); chamber_dxdz_trackdydz.Merge(tlist)

    chamber_x_trackx.SetAxisRange(-14.99, 14.99, "Y")
    chamber_dxdz_trackx.SetAxisRange(-7.5, 7.5, "Y")
    chamber_x_tracky.SetAxisRange(-14.99, 14.99, "Y")
    chamber_dxdz_tracky.SetAxisRange(-7.5, 7.5, "Y")
    chamber_x_trackdxdz.SetAxisRange(-14.99, 14.99, "Y")
    chamber_dxdz_trackdxdz.SetAxisRange(-7.5, 7.5, "Y")
    chamber_x_trackdydz.SetAxisRange(-14.99, 14.99, "Y")
    chamber_dxdz_trackdydz.SetAxisRange(-7.5, 7.5, "Y")

    if chamber_y_trackx is not None:
        chamber_y_trackx.SetAxisRange(-24.99, 24.99, "Y")
        chamber_dydz_trackx.SetAxisRange(-24.99, 24.99, "Y")
        chamber_y_tracky.SetAxisRange(-24.99, 24.99, "Y")
        chamber_dydz_tracky.SetAxisRange(-24.99, 24.99, "Y")
        chamber_y_trackdxdz.SetAxisRange(-24.99, 24.99, "Y")
        chamber_dydz_trackdxdz.SetAxisRange(-24.99, 24.99, "Y")
        chamber_y_trackdydz.SetAxisRange(-24.99, 24.99, "Y")
        chamber_dydz_trackdydz.SetAxisRange(-24.99, 24.99, "Y")

    for h in chamber_x_trackx, chamber_y_trackx, chamber_dxdz_trackx, chamber_dydz_trackx, chamber_x_tracky, chamber_y_tracky, chamber_dxdz_tracky, chamber_dydz_tracky, chamber_x_trackdxdz, chamber_y_trackdxdz, chamber_dxdz_trackdxdz, chamber_dydz_trackdxdz, chamber_x_trackdydz, chamber_y_trackdydz, chamber_dxdz_trackdydz, chamber_dydz_trackdydz:
        if h is not None:
            h.SetMarkerStyle(20)
            h.SetMarkerSize(0.5)
            h.GetXaxis().SetLabelSize(0.13)
            h.GetYaxis().SetLabelSize(0.13)
            h.GetXaxis().SetNdivisions(505)
            h.GetYaxis().SetNdivisions(505)
            h.GetXaxis().SetLabelOffset(0.03)
            h.GetYaxis().SetLabelOffset(0.03)

    trackdxdz_minimum, trackdxdz_maximum = None, None
    for h in chamber_x_trackdxdz, chamber_y_trackdxdz, chamber_dxdz_trackdxdz, chamber_dydz_trackdxdz:
        if h is not None:
            for i in xrange(1, h.GetNbinsX()+1):
                if h.GetBinError(i) > 0.01 and h.GetBinContent(i) - h.GetBinError(i) < 10. and h.GetBinContent(i) + h.GetBinError(i) > -10.:
                    if trackdxdz_minimum is None or trackdxdz_minimum > h.GetBinCenter(i): trackdxdz_minimum = h.GetBinCenter(i)
                    if trackdxdz_maximum < h.GetBinCenter(i): trackdxdz_maximum = h.GetBinCenter(i)
    if trackdxdz_minimum is not None and trackdxdz_maximum is not None:
        for h in chamber_x_trackdxdz, chamber_y_trackdxdz, chamber_dxdz_trackdxdz, chamber_dydz_trackdxdz:
            if h is not None:
                h.SetAxisRange(trackdxdz_minimum, trackdxdz_maximum, "X")

    trackdydz_minimum, trackdydz_maximum = None, None
    for h in chamber_x_trackdydz, chamber_y_trackdydz, chamber_dxdz_trackdydz, chamber_dydz_trackdydz:
        if h is not None:
            for i in xrange(1, h.GetNbinsX()+1):
                if h.GetBinError(i) > 0.01 and h.GetBinContent(i) - h.GetBinError(i) < 10. and h.GetBinContent(i) + h.GetBinError(i) > -10.:
                    if trackdydz_minimum is None or trackdydz_minimum > h.GetBinCenter(i): trackdydz_minimum = h.GetBinCenter(i)
                    if trackdydz_maximum < h.GetBinCenter(i): trackdydz_maximum = h.GetBinCenter(i)
    if trackdydz_minimum is not None and trackdydz_maximum is not None:
        for h in chamber_x_trackdydz, chamber_y_trackdydz, chamber_dxdz_trackdydz, chamber_dydz_trackdydz:
            if h is not None:
                h.SetAxisRange(trackdydz_minimum, trackdydz_maximum, "X")

    for f in chamber_x_trackx_fit2, chamber_y_trackx_fit2, chamber_dxdz_trackx_fit2, chamber_dydz_trackx_fit2, chamber_x_tracky_fit2, chamber_y_tracky_fit2, chamber_dxdz_tracky_fit2, chamber_dydz_tracky_fit2, chamber_x_trackdxdz_fit2, chamber_y_trackdxdz_fit2, chamber_dxdz_trackdxdz_fit2, chamber_dydz_trackdxdz_fit2, chamber_x_trackdydz_fit2, chamber_y_trackdydz_fit2, chamber_dxdz_trackdydz_fit2, chamber_dydz_trackdydz_fit2:
        if f is not None:
            f.SetLineColor(4)

    if chamber_y_trackx is not None:
        c1.Clear()
        c1.Divide(5, 5, 1e-5, 1e-5)

        label1 = ROOT.TPaveLabel(0, 0, 1, 1, "x residuals (mm)")
        label2 = ROOT.TPaveLabel(0, 0, 1, 1, "y residuals (mm)")
        label3 = ROOT.TPaveLabel(0, 0, 1, 1, "dx/dz residuals (mrad)")
        label4 = ROOT.TPaveLabel(0, 0, 1, 1, "dy/dz residuals (mrad)")
        label5 = ROOT.TPaveLabel(0, 0.5, 1, 1, "x position (cm)")
        label6 = ROOT.TPaveLabel(0, 0.5, 1, 1, "y position (cm)")
        label7 = ROOT.TPaveLabel(0, 0.5, 1, 1, "dx/dz angle (rad)")
        label8 = ROOT.TPaveLabel(0, 0.5, 1, 1, "dy/dz angle (rad)")
        label9 = ROOT.TPaveLabel(0, 0, 1, 1, getname(r))

        for l in label1, label2, label3, label4, label5, label6, label7, label8, label9:
            l.SetBorderSize(0)
            l.SetFillColor(ROOT.kWhite)

        label9.SetTextAngle(30)

        c1.GetPad(1).cd(); label1.Draw()
        c1.GetPad(6).cd(); label2.Draw()
        c1.GetPad(11).cd(); label3.Draw()
        c1.GetPad(16).cd(); label4.Draw()
        c1.GetPad(22).cd(); label5.Draw()
        c1.GetPad(23).cd(); label6.Draw()
        c1.GetPad(24).cd(); label7.Draw()
        c1.GetPad(25).cd(); label8.Draw()
        c1.GetPad(21).cd(); label9.Draw()

        c1.GetPad(2).SetRightMargin(1e-5)
        c1.GetPad(2).SetBottomMargin(1e-5)
        c1.GetPad(3).SetLeftMargin(1e-5)
        c1.GetPad(3).SetRightMargin(1e-5)
        c1.GetPad(3).SetBottomMargin(1e-5)
        c1.GetPad(4).SetLeftMargin(1e-5)
        c1.GetPad(4).SetRightMargin(1e-5)
        c1.GetPad(4).SetBottomMargin(1e-5)
        c1.GetPad(5).SetLeftMargin(1e-5)
        c1.GetPad(5).SetBottomMargin(1e-5)

        c1.GetPad(7).SetRightMargin(1e-5)
        c1.GetPad(7).SetBottomMargin(1e-5)
        c1.GetPad(7).SetTopMargin(1e-5)
        c1.GetPad(8).SetLeftMargin(1e-5)
        c1.GetPad(8).SetRightMargin(1e-5)
        c1.GetPad(8).SetBottomMargin(1e-5)
        c1.GetPad(8).SetTopMargin(1e-5)
        c1.GetPad(9).SetLeftMargin(1e-5)
        c1.GetPad(9).SetRightMargin(1e-5)
        c1.GetPad(9).SetBottomMargin(1e-5)
        c1.GetPad(9).SetTopMargin(1e-5)
        c1.GetPad(10).SetLeftMargin(1e-5)
        c1.GetPad(10).SetBottomMargin(1e-5)
        c1.GetPad(10).SetTopMargin(1e-5)

        c1.GetPad(12).SetRightMargin(1e-5)
        c1.GetPad(12).SetBottomMargin(1e-5)
        c1.GetPad(12).SetTopMargin(1e-5)
        c1.GetPad(13).SetLeftMargin(1e-5)
        c1.GetPad(13).SetRightMargin(1e-5)
        c1.GetPad(13).SetBottomMargin(1e-5)
        c1.GetPad(13).SetTopMargin(1e-5)
        c1.GetPad(14).SetLeftMargin(1e-5)
        c1.GetPad(14).SetRightMargin(1e-5)
        c1.GetPad(14).SetBottomMargin(1e-5)
        c1.GetPad(14).SetTopMargin(1e-5)
        c1.GetPad(15).SetLeftMargin(1e-5)
        c1.GetPad(15).SetBottomMargin(1e-5)
        c1.GetPad(15).SetTopMargin(1e-5)

        c1.GetPad(17).SetRightMargin(1e-5)
        c1.GetPad(17).SetTopMargin(1e-5)
        c1.GetPad(18).SetLeftMargin(1e-5)
        c1.GetPad(18).SetRightMargin(1e-5)
        c1.GetPad(18).SetTopMargin(1e-5)
        c1.GetPad(19).SetLeftMargin(1e-5)
        c1.GetPad(19).SetRightMargin(1e-5)
        c1.GetPad(19).SetTopMargin(1e-5)
        c1.GetPad(20).SetLeftMargin(1e-5)
        c1.GetPad(20).SetTopMargin(1e-5)
        
        chamber_x_trackx.GetXaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_tracky.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_trackdxdz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_trackdydz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_y_trackx.GetXaxis().SetLabelColor(ROOT.kWhite)
        chamber_y_tracky.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_y_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_y_trackdxdz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_y_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_y_trackdydz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_y_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_trackx.GetXaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_tracky.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_dxdz_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_trackdxdz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_dxdz_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_trackdydz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_dxdz_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)
        # chamber_dydz_trackx
        chamber_dydz_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dydz_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dydz_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)

        c1.GetPad(2).cd(); chamber_x_trackx.Draw("e1"); (None if suppressblue else chamber_x_trackx_fit2.Draw("samel")); chamber_x_trackx_fit.Draw("samel")
        c1.GetPad(3).cd(); chamber_x_tracky.Draw("e1"); (None if suppressblue else chamber_x_tracky_fit2.Draw("samel")); chamber_x_tracky_fit.Draw("samel")
        c1.GetPad(4).cd(); chamber_x_trackdxdz.Draw("e1"); (None if suppressblue else chamber_x_trackdxdz_fit2.Draw("samel")); chamber_x_trackdxdz_fit.Draw("samel")
        c1.GetPad(5).cd(); chamber_x_trackdydz.Draw("e1"); (None if suppressblue else chamber_x_trackdydz_fit2.Draw("samel")); chamber_x_trackdydz_fit.Draw("samel")
        c1.GetPad(7).cd(); chamber_y_trackx.Draw("e1"); (None if suppressblue else chamber_y_trackx_fit2.Draw("samel")); chamber_y_trackx_fit.Draw("samel")
        c1.GetPad(8).cd(); chamber_y_tracky.Draw("e1"); (None if suppressblue else chamber_y_tracky_fit2.Draw("samel")); chamber_y_tracky_fit.Draw("samel")
        c1.GetPad(9).cd(); chamber_y_trackdxdz.Draw("e1"); (None if suppressblue else chamber_y_trackdxdz_fit2.Draw("samel")); chamber_y_trackdxdz_fit.Draw("samel")
        c1.GetPad(10).cd(); chamber_y_trackdydz.Draw("e1"); (None if suppressblue else chamber_y_trackdydz_fit2.Draw("samel")); chamber_y_trackdydz_fit.Draw("samel")
        c1.GetPad(12).cd(); chamber_dxdz_trackx.Draw("e1"); (None if suppressblue else chamber_dxdz_trackx_fit2.Draw("samel")); chamber_dxdz_trackx_fit.Draw("samel")
        c1.GetPad(13).cd(); chamber_dxdz_tracky.Draw("e1"); (None if suppressblue else chamber_dxdz_tracky_fit2.Draw("samel")); chamber_dxdz_tracky_fit.Draw("samel")
        c1.GetPad(14).cd(); chamber_dxdz_trackdxdz.Draw("e1"); (None if suppressblue else chamber_dxdz_trackdxdz_fit2.Draw("samel")); chamber_dxdz_trackdxdz_fit.Draw("samel")
        c1.GetPad(15).cd(); chamber_dxdz_trackdydz.Draw("e1"); (None if suppressblue else chamber_dxdz_trackdydz_fit2.Draw("samel")); chamber_dxdz_trackdydz_fit.Draw("samel")
        c1.GetPad(17).cd(); chamber_dydz_trackx.Draw("e1"); (None if suppressblue else chamber_dydz_trackx_fit2.Draw("samel")); chamber_dydz_trackx_fit.Draw("samel")
        c1.GetPad(18).cd(); chamber_dydz_tracky.Draw("e1"); (None if suppressblue else chamber_dydz_tracky_fit2.Draw("samel")); chamber_dydz_tracky_fit.Draw("samel")
        c1.GetPad(19).cd(); chamber_dydz_trackdxdz.Draw("e1"); (None if suppressblue else chamber_dydz_trackdxdz_fit2.Draw("samel")); chamber_dydz_trackdxdz_fit.Draw("samel")
        c1.GetPad(20).cd(); chamber_dydz_trackdydz.Draw("e1"); (None if suppressblue else chamber_dydz_trackdydz_fit2.Draw("samel")); chamber_dydz_trackdydz_fit.Draw("samel")

    else:
        c1.Clear()
        c1.Divide(5, 3, 1e-5, 1e-5)

        label1 = ROOT.TPaveLabel(0, 0, 1, 1, "x residuals (mm)")
        label2 = ROOT.TPaveLabel(0, 0, 1, 1, "dx/dz residuals (mrad)")
        label3 = ROOT.TPaveLabel(0, 0.5, 1, 1, "x position (cm)")
        label4 = ROOT.TPaveLabel(0, 0.5, 1, 1, "y position (cm)")
        label5 = ROOT.TPaveLabel(0, 0.5, 1, 1, "dx/dz angle (rad)")
        label6 = ROOT.TPaveLabel(0, 0.5, 1, 1, "dy/dz angle (rad)")
        label9 = ROOT.TPaveLabel(0, 0.5, 1, 1, getname(r))

        if name[0:2] == "ME":
            label1 = ROOT.TPaveLabel(0, 0, 1, 1, "r#phi residuals (mm)")
            label2 = ROOT.TPaveLabel(0, 0, 1, 1, "d(r#phi)/dz residuals (mrad)")

        for l in label1, label2, label3, label4, label5, label6, label9:
            l.SetBorderSize(0)
            l.SetFillColor(ROOT.kWhite)

        label9.SetTextAngle(30)

        c1.GetPad(1).cd(); label1.Draw()
        c1.GetPad(6).cd(); label2.Draw()
        c1.GetPad(12).cd(); label3.Draw()
        c1.GetPad(13).cd(); label4.Draw()
        c1.GetPad(14).cd(); label5.Draw()
        c1.GetPad(15).cd(); label6.Draw()
        c1.GetPad(11).cd(); label9.Draw()

        c1.GetPad(2).SetRightMargin(1e-5)
        c1.GetPad(2).SetBottomMargin(1e-5)
        c1.GetPad(3).SetLeftMargin(1e-5)
        c1.GetPad(3).SetRightMargin(1e-5)
        c1.GetPad(3).SetBottomMargin(1e-5)
        c1.GetPad(4).SetLeftMargin(1e-5)
        c1.GetPad(4).SetRightMargin(1e-5)
        c1.GetPad(4).SetBottomMargin(1e-5)
        c1.GetPad(5).SetLeftMargin(1e-5)
        c1.GetPad(5).SetBottomMargin(1e-5)

        c1.GetPad(7).SetRightMargin(1e-5)
        c1.GetPad(7).SetTopMargin(1e-5)
        c1.GetPad(8).SetLeftMargin(1e-5)
        c1.GetPad(8).SetRightMargin(1e-5)
        c1.GetPad(8).SetTopMargin(1e-5)
        c1.GetPad(9).SetLeftMargin(1e-5)
        c1.GetPad(9).SetRightMargin(1e-5)
        c1.GetPad(9).SetTopMargin(1e-5)
        c1.GetPad(10).SetLeftMargin(1e-5)
        c1.GetPad(10).SetTopMargin(1e-5)

        chamber_x_trackx.GetXaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_tracky.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_trackdxdz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_x_trackdydz.GetXaxis().SetLabelColor(ROOT.kWhite); chamber_x_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)
        # chamber_dxdz_trackx
        chamber_dxdz_tracky.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_trackdxdz.GetYaxis().SetLabelColor(ROOT.kWhite)
        chamber_dxdz_trackdydz.GetYaxis().SetLabelColor(ROOT.kWhite)

        c1.GetPad(2).cd(); chamber_x_trackx.Draw("e1"); (None if suppressblue else chamber_x_trackx_fit2.Draw("samel")); chamber_x_trackx_fit.Draw("samel")
        c1.GetPad(3).cd(); chamber_x_tracky.Draw("e1"); (None if suppressblue else chamber_x_tracky_fit2.Draw("samel")); chamber_x_tracky_fit.Draw("samel")
        c1.GetPad(4).cd(); chamber_x_trackdxdz.Draw("e1"); (None if suppressblue else chamber_x_trackdxdz_fit2.Draw("samel")); chamber_x_trackdxdz_fit.Draw("samel")
        c1.GetPad(5).cd(); chamber_x_trackdydz.Draw("e1"); (None if suppressblue else chamber_x_trackdydz_fit2.Draw("samel")); chamber_x_trackdydz_fit.Draw("samel")
        c1.GetPad(7).cd(); chamber_dxdz_trackx.Draw("e1"); (None if suppressblue else chamber_dxdz_trackx_fit2.Draw("samel")); chamber_dxdz_trackx_fit.Draw("samel")
        c1.GetPad(8).cd(); chamber_dxdz_tracky.Draw("e1"); (None if suppressblue else chamber_dxdz_tracky_fit2.Draw("samel")); chamber_dxdz_tracky_fit.Draw("samel")
        c1.GetPad(9).cd(); chamber_dxdz_trackdxdz.Draw("e1"); (None if suppressblue else chamber_dxdz_trackdxdz_fit2.Draw("samel")); chamber_dxdz_trackdxdz_fit.Draw("samel")
        c1.GetPad(10).cd(); chamber_dxdz_trackdydz.Draw("e1"); (None if suppressblue else chamber_dxdz_trackdydz_fit2.Draw("samel")); chamber_dxdz_trackdydz_fit.Draw("samel")

##########################################################################

# HERE

tdrStyle.SetOptFit(0)

all_x = ROOT.TH1F("all_x", "", 100, -100, 100)
all_y = ROOT.TH1F("all_y", "", 100, -200, 200)
all_dxdz = ROOT.TH1F("all_dxdz", "", 100, -100, 100)
all_dydz = ROOT.TH1F("all_dydz", "", 100, -200, 200)

mean_x = []
mean_y = []
mean_dxdz = []
mean_dydz = []
peak_x = []
peak_y = []
peak_dxdz = []
peak_dydz = []
sigma_x = []
sigma_y = []
sigma_dxdz = []
sigma_dydz = []
for r in reports:
    if r.status == "PASS":
        chamber_x = tfile.Get("%s/%s%s_x" % (plotDirectory, r.name, ""))
        if chamber_x is None:
            chamber_x = tfile.Get("%s/%s%s_residual" % (plotDirectory, r.name, ""))
            chamber_dxdz = tfile.Get("%s/%s%s_resslope" % (plotDirectory, r.name, ""))
            all_x.Add(chamber_x)
            all_dxdz.Add(chamber_dxdz)
        else:
            chamber_y = tfile.Get("%s/%s%s_y" % (plotDirectory, r.name, ""))
            chamber_dxdz = tfile.Get("%s/%s%s_dxdz" % (plotDirectory, r.name, ""))
            chamber_dydz = tfile.Get("%s/%s%s_dydz" % (plotDirectory, r.name, ""))
            all_x.Add(chamber_x)
            all_y.Add(chamber_y)
            all_dxdz.Add(chamber_dxdz)
            all_dydz.Add(chamber_dydz)

            f = ROOT.TF1("f", ROOT.voigt, -100, 100, 4)
            f.SetParameters(chamber_y.GetNbinsX(), chamber_y.GetMean(), chamber_y.GetRMS())
            chamber_y.Fit("f")
            mean_y.append(chamber_y.GetMean())
            peak_y.append(chamber_y.GetFunction("f").GetParameter(1))
            sigma_y.append(chamber_y.GetFunction("f").GetParameter(2))

            f = ROOT.TF1("f", ROOT.voigt, -100, 100, 4)
            f.SetParameters(chamber_dydz.GetNbinsX(), chamber_dydz.GetMean(), chamber_dydz.GetRMS())
            chamber_dydz.Fit("f")
            mean_dydz.append(chamber_dydz.GetMean())
            peak_dydz.append(chamber_dydz.GetFunction("f").GetParameter(1))
            sigma_dydz.append(chamber_dydz.GetFunction("f").GetParameter(2))

        f = ROOT.TF1("f", ROOT.voigt, -100, 100, 4)
        f.SetParameters(chamber_x.GetNbinsX(), chamber_x.GetMean(), chamber_x.GetRMS())
        chamber_x.Fit("f")
        mean_x.append(chamber_x.GetMean())
        peak_x.append(chamber_x.GetFunction("f").GetParameter(1))
        sigma_x.append(chamber_x.GetFunction("f").GetParameter(2))

        f = ROOT.TF1("f", ROOT.voigt, -100, 100, 4)
        f.SetParameters(chamber_dxdz.GetNbinsX(), chamber_dxdz.GetMean(), chamber_dxdz.GetRMS())
        chamber_dxdz.Fit("f")
        mean_dxdz.append(chamber_dxdz.GetMean())
        peak_dxdz.append(chamber_dxdz.GetFunction("f").GetParameter(1))
        sigma_dxdz.append(chamber_dxdz.GetFunction("f").GetParameter(2))

for h in all_x, all_y, all_dxdz, all_dydz:
    entries = float(h.GetEntries())
    for i in xrange(1, h.GetNbinsX()+1):
        h.SetBinContent(i, h.GetBinContent(i)/entries)
        h.SetBinError(i, h.GetBinError(i)/entries)

c1.SetLogy(1)
all_x.Draw()
all_y.Draw()
all_dxdz.Draw()
all_dydz.Draw()

func = ROOT.TF1("func", ROOT.extendedvoigt, -30.1, 30, 5)
func.SetParNames("Normalization", "Peak", "Sigma", "Gamma", "Power")
func.SetParameters(1., all_x.GetMean(), all_x.GetRMS(), 0.1*all_x.GetRMS(), 2.)
all_x.Fit("func", "R")

func = ROOT.TF1("func", ROOT.extendedvoigt, -30.1, 30, 5)
func.SetParNames("Normalization", "Peak", "Sigma", "Gamma", "Power")
func.SetParameters(1., all_y.GetMean(), all_y.GetRMS(), 0.1*all_y.GetRMS(), 2.)
all_y.Fit("func", "R")

func = ROOT.TF1("func", ROOT.extendedvoigt, -20.1, 20, 5)
func.SetParNames("Normalization", "Peak", "Sigma", "Gamma", "Power")
func.SetParameters(1., all_dxdz.GetMean(), all_dxdz.GetRMS(), 0.1*all_dxdz.GetRMS(), 2.)
all_dxdz.Fit("func", "R")

func = ROOT.TF1("func", ROOT.extendedvoigt, -50.1, 50, 5)
func.SetParNames("Normalization", "Peak", "Sigma", "Gamma", "Power")
func.SetParameters(1., all_dydz.GetMean(), all_dydz.GetRMS(), 0.1*all_dydz.GetRMS(), 2.)
all_dydz.Fit("func", "R")

all_x.SetXTitle("\Deltax (mm)")
all_y.SetXTitle("\Deltay (mm)")
all_dxdz.SetXTitle("\Deltadx/dz (mrad)")
all_dydz.SetXTitle("\Deltady/dz (mrad)")
all_x.SetYTitle("Normalized entries")
all_y.SetYTitle("Normalized entries")
all_dxdz.SetYTitle("Normalized entries")
all_dydz.SetYTitle("Normalized entries")
all_x.GetXaxis().CenterTitle()
all_y.GetXaxis().CenterTitle()
all_dxdz.GetXaxis().CenterTitle()
all_dydz.GetXaxis().CenterTitle()
all_x.GetYaxis().CenterTitle()
all_y.GetYaxis().CenterTitle()
all_dxdz.GetYaxis().CenterTitle()
all_dydz.GetYaxis().CenterTitle()
all_x.GetYaxis().SetTitleOffset(1.5)
all_y.GetYaxis().SetTitleOffset(1.5)
all_dxdz.GetYaxis().SetTitleOffset(1.5)
all_dydz.GetYaxis().SetTitleOffset(1.5)

all_x.Draw("e1")
all_y.Draw("e1")
all_dxdz.Draw("e1")
all_dydz.Draw("e1")

databefore_tfile = tfile
for s in "all_x", "all_dxdz", "all_y", "all_dydz", "mean_x", "mean_dxdz", "mean_y", "mean_dydz", "peak_x", "peak_dxdz", "peak_y", "peak_dydz", "sigma_x", "sigma_dxdz", "sigma_y", "sigma_dydz": exec("databefore_%s = %s" % (s, s))

dataafter_tfile = tfile
for s in "all_x", "all_dxdz", "all_y", "all_dydz", "mean_x", "mean_dxdz", "mean_y", "mean_dydz", "peak_x", "peak_dxdz", "peak_y", "peak_dydz", "sigma_x", "sigma_dxdz", "sigma_y", "sigma_dydz": exec("dataafter_%s = %s" % (s, s))

mcafter_tfile = tfile
for s in "all_x", "all_dxdz", "all_y", "all_dydz", "mean_x", "mean_dxdz", "mean_y", "mean_dydz", "peak_x", "peak_dxdz", "peak_y", "peak_dydz", "sigma_x", "sigma_dxdz", "sigma_y", "sigma_dydz": exec("mcafter_%s = %s" % (s, s))

millepede_tfile = tfile
for s in "all_x", "all_dxdz", "all_y", "all_dydz", "mean_x", "mean_dxdz", "mean_y", "mean_dydz", "peak_x", "peak_dxdz", "peak_y", "peak_dydz", "sigma_x", "sigma_dxdz", "sigma_y", "sigma_dydz": exec("millepede_%s = %s" % (s, s))

for h in databefore_all_x, databefore_all_dxdz, databefore_all_y, databefore_all_dydz:
    h.SetMarkerStyle(5)
    h.SetMarkerSize(1.7)
    h.SetMarkerColor(ROOT.kRed)
    h.SetLineColor(ROOT.kRed)
    h.GetFunction("func").SetLineColor(ROOT.kRed)
    h.GetFunction("func").SetLineStyle(1)
    h.SetLineStyle(1)
for h in dataafter_all_x, dataafter_all_dxdz, dataafter_all_y, dataafter_all_dydz:
    h.SetMarkerStyle(20)
    h.SetMarkerSize(1.7)
    h.SetMarkerColor(ROOT.kBlack)
    h.SetLineColor(ROOT.kBlack)
    h.GetFunction("func").SetLineColor(ROOT.kBlack)
    h.GetFunction("func").SetLineStyle(1)
    h.SetLineStyle(1)
for h in mcafter_all_x, mcafter_all_dxdz, mcafter_all_y, mcafter_all_dydz:
    h.SetMarkerStyle(24)
    h.SetMarkerSize(1.7)
    h.SetMarkerColor(ROOT.kGreen+2)
    h.SetLineColor(ROOT.kGreen+2)
    h.GetFunction("func").SetLineColor(ROOT.kGreen+2)
    h.GetFunction("func").SetLineStyle(3)
    h.SetLineStyle(3)
for h in millepede_all_x, millepede_all_dxdz, millepede_all_y, millepede_all_dydz:
    h.SetMarkerStyle(21)
    h.SetMarkerSize(1.7)
    h.SetMarkerColor(ROOT.kBlue)
    h.SetLineColor(ROOT.kBlue)
    h.GetFunction("func").SetLineColor(ROOT.kBlue)
    h.GetFunction("func").SetLineStyle(2)
    h.SetLineStyle(2)

#########################

# for h in databefore_all_x, databefore_all_y, databefore_all_dxdz, databefore_all_dydz:
#     print "& %4.2f & %4.2f & %4.2f & %4.2f \\\\" % (h.GetRMS(), h.GetFunction("func").GetParameter(2) * sqrt(h.GetFunction("func").GetParameter(4)/2), h.GetFunction("func").GetParameter(3), h.GetFunction("func").GetParameter(4))

# for h in dataafter_all_x, dataafter_all_y, dataafter_all_dxdz, dataafter_all_dydz:
#     print "& %4.2f & %4.2f & %4.2f & %4.2f \\\\" % (h.GetRMS(), h.GetFunction("func").GetParameter(2) * sqrt(h.GetFunction("func").GetParameter(4)/2), h.GetFunction("func").GetParameter(3), h.GetFunction("func").GetParameter(4))

# for h in millepede_all_x, millepede_all_y, millepede_all_dxdz, millepede_all_dydz:
#     print "& %4.2f & %4.2f & %4.2f & %4.2f \\\\" % (h.GetRMS(), h.GetFunction("func").GetParameter(2) * sqrt(h.GetFunction("func").GetParameter(4)/2), h.GetFunction("func").GetParameter(3), h.GetFunction("func").GetParameter(4))

# for h in mcafter_all_x, mcafter_all_y, mcafter_all_dxdz, mcafter_all_dydz:
#     print "& %4.2f & %4.2f & %4.2f & %4.2f \\\\" % (h.GetRMS(), h.GetFunction("func").GetParameter(2) * sqrt(h.GetFunction("func").GetParameter(4)/2), h.GetFunction("func").GetParameter(3), h.GetFunction("func").GetParameter(4))

for h in databefore_all_x, databefore_all_y, databefore_all_dxdz, databefore_all_dydz:
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h.GetMean(), h.GetRMS(), h.GetFunction("func").GetParameter(4))

for h in dataafter_all_x, dataafter_all_y, dataafter_all_dxdz, dataafter_all_dydz:
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h.GetMean(), h.GetRMS(), h.GetFunction("func").GetParameter(4))

for h in millepede_all_x, millepede_all_y, millepede_all_dxdz, millepede_all_dydz:
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h.GetMean(), h.GetRMS(), h.GetFunction("func").GetParameter(4))

for h in mcafter_all_x, mcafter_all_y, mcafter_all_dxdz, mcafter_all_dydz:
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h.GetMean(), h.GetRMS(), h.GetFunction("func").GetParameter(4))

#########################

databefore_all_x.SetYTitle("Segments / 2 mm (normalized)")
databefore_all_y.SetYTitle("Segments / 4 mm (normalized)")
databefore_all_dxdz.SetYTitle("Segments / 2 mrad (normalized)")
databefore_all_dydz.SetYTitle("Segments / 4 mrad (normalized)")

tlegend = ROOT.TLegend(0.45, 0.8, 0.98, 0.98)
tlegend.SetBorderSize(1)
tlegend.SetFillColor(ROOT.kWhite)
tlegend.AddEntry(dataafter_all_x, "Reference-Target alignment", "pl")
tlegend.AddEntry(millepede_all_x, "Millepede alignment", "pl")
tlegend.AddEntry(mcafter_all_x, "aligned Monte Carlo (R-T)", "pl")
tlegend.AddEntry(databefore_all_x, "unaligned data", "pl")
tlegend.SetTextSize(0.04)

c1.SetLogy(0)

databefore_all_x.SetAxisRange(-30.1, 30, "X")
databefore_all_x.SetAxisRange(0, 0.25, "Y")
databefore_all_x.Draw("e1")
mcafter_all_x.Draw("e1same")
millepede_all_x.Draw("e1same")
dataafter_all_x.Draw("e1same")
c1.SaveAs("finalresiduals_all_x.pdf")

databefore_all_y.SetAxisRange(-30.1, 30, "X")
databefore_all_y.SetAxisRange(0, 0.3, "Y")
databefore_all_y.Draw("e1")
mcafter_all_y.Draw("e1same")
millepede_all_y.Draw("e1same")
dataafter_all_y.Draw("e1same")
c1.SaveAs("finalresiduals_all_y.pdf")

databefore_all_dxdz.SetAxisRange(-20.1, 20, "X")
databefore_all_dxdz.SetAxisRange(0, 0.35, "Y")
databefore_all_dxdz.Draw("e1")
mcafter_all_dxdz.Draw("e1same")
millepede_all_dxdz.Draw("e1same")
dataafter_all_dxdz.Draw("e1same")
c1.SaveAs("finalresiduals_all_dxdz.pdf")

databefore_all_dydz.SetAxisRange(-50, 50, "X")
databefore_all_dydz.SetAxisRange(0, 0.12, "Y")
databefore_all_dydz.Draw("e1")
mcafter_all_dydz.Draw("e1same")
millepede_all_dydz.Draw("e1same")
dataafter_all_dydz.Draw("e1same")
tlegend.Draw()
c1.SaveAs("finalresiduals_all_dydz.pdf")

c1.SetLogy(1)

databefore_all_x.SetAxisRange(-29.1, 29, "X")
databefore_all_x.SetAxisRange(5e-6, 1, "Y")
databefore_all_x.Draw("e1")
mcafter_all_x.Draw("e1same")
millepede_all_x.Draw("e1same")
dataafter_all_x.Draw("e1same")
c1.SaveAs("finalresiduals_alllogy_x.pdf")

databefore_all_y.SetAxisRange(-30.1, 30, "X")
databefore_all_y.SetAxisRange(5e-5, 1, "Y")
databefore_all_y.Draw("e1")
mcafter_all_y.Draw("e1same")
millepede_all_y.Draw("e1same")
dataafter_all_y.Draw("e1same")
c1.SaveAs("finalresiduals_alllogy_y.pdf")

databefore_all_dxdz.SetAxisRange(-20.1, 20, "X")
databefore_all_dxdz.SetAxisRange(5e-6, 10, "Y")
databefore_all_dxdz.Draw("e1")
mcafter_all_dxdz.Draw("e1same")
millepede_all_dxdz.Draw("e1same")
dataafter_all_dxdz.Draw("e1same")
tlegend.Draw()
c1.SaveAs("finalresiduals_alllogy_dxdz.pdf")

databefore_all_dydz.SetAxisRange(-50, 50, "X")
databefore_all_dydz.SetAxisRange(1e-4, 1, "Y")
databefore_all_dydz.Draw("e1")
mcafter_all_dydz.Draw("e1same")
millepede_all_dydz.Draw("e1same")
dataafter_all_dydz.Draw("e1same")
c1.SaveAs("finalresiduals_alllogy_dydz.pdf")

c1.SetLogy(0)

##################################

h_databefore_mean_x = ROOT.TH1F("databefore_mean_x", "", 50, -3, 3)
h_dataafter_mean_x = ROOT.TH1F("dataafter_mean_x", "", 50, -3, 3)
h_mcafter_mean_x = ROOT.TH1F("mcafter_mean_x", "", 50, -3, 3)
h_millepede_mean_x = ROOT.TH1F("millepede_mean_x", "", 50, -3, 3)
h_databefore_mean_y = ROOT.TH1F("databefore_mean_y", "", 50, -3, 3)
h_dataafter_mean_y = ROOT.TH1F("dataafter_mean_y", "", 50, -3, 3)
h_mcafter_mean_y = ROOT.TH1F("mcafter_mean_y", "", 50, -3, 3)
h_millepede_mean_y = ROOT.TH1F("millepede_mean_y", "", 50, -3, 3)
h_databefore_mean_dxdz = ROOT.TH1F("databefore_mean_dxdz", "", 50, -3, 3)
h_dataafter_mean_dxdz = ROOT.TH1F("dataafter_mean_dxdz", "", 50, -3, 3)
h_mcafter_mean_dxdz = ROOT.TH1F("mcafter_mean_dxdz", "", 50, -3, 3)
h_millepede_mean_dxdz = ROOT.TH1F("millepede_mean_dxdz", "", 50, -3, 3)
h_databefore_mean_dydz = ROOT.TH1F("databefore_mean_dydz", "", 50, -5, 5)
h_dataafter_mean_dydz = ROOT.TH1F("dataafter_mean_dydz", "", 50, -5, 5)
h_mcafter_mean_dydz = ROOT.TH1F("mcafter_mean_dydz", "", 50, -5, 5)
h_millepede_mean_dydz = ROOT.TH1F("millepede_mean_dydz", "", 50, -5, 5)

for x in databefore_mean_x: h_databefore_mean_x.Fill(x)
for x in dataafter_mean_x: h_dataafter_mean_x.Fill(x)
for x in mcafter_mean_x: h_mcafter_mean_x.Fill(x)
for x in millepede_mean_x: h_millepede_mean_x.Fill(x)
for x in databefore_mean_y: h_databefore_mean_y.Fill(x)
for x in dataafter_mean_y: h_dataafter_mean_y.Fill(x)
for x in mcafter_mean_y: h_mcafter_mean_y.Fill(x)
for x in millepede_mean_y: h_millepede_mean_y.Fill(x)
for x in databefore_mean_dxdz: h_databefore_mean_dxdz.Fill(x)
for x in dataafter_mean_dxdz: h_dataafter_mean_dxdz.Fill(x)
for x in mcafter_mean_dxdz: h_mcafter_mean_dxdz.Fill(x)
for x in millepede_mean_dxdz: h_millepede_mean_dxdz.Fill(x)
for x in databefore_mean_dydz: h_databefore_mean_dydz.Fill(x)
for x in dataafter_mean_dydz: h_dataafter_mean_dydz.Fill(x)
for x in mcafter_mean_dydz: h_mcafter_mean_dydz.Fill(x)
for x in millepede_mean_dydz: h_millepede_mean_dydz.Fill(x)

h_dataafter_mean_x.SetLineColor(ROOT.kBlack)
h_databefore_mean_x.SetFillColor(ROOT.kRed)
h_mcafter_mean_x.SetLineStyle(3)
h_mcafter_mean_x.SetLineColor(ROOT.kGreen+2)
h_millepede_mean_x.SetLineStyle(2)
h_millepede_mean_x.SetLineColor(ROOT.kBlue)
h_dataafter_mean_y.SetLineColor(ROOT.kBlack)
h_databefore_mean_y.SetFillColor(ROOT.kRed)
h_mcafter_mean_y.SetLineStyle(3)
h_mcafter_mean_y.SetLineColor(ROOT.kGreen+2)
h_millepede_mean_y.SetLineStyle(2)
h_millepede_mean_y.SetLineColor(ROOT.kBlue)
h_dataafter_mean_dxdz.SetLineColor(ROOT.kBlack)
h_databefore_mean_dxdz.SetFillColor(ROOT.kRed)
h_mcafter_mean_dxdz.SetLineStyle(3)
h_mcafter_mean_dxdz.SetLineColor(ROOT.kGreen+2)
h_millepede_mean_dxdz.SetLineStyle(2)
h_millepede_mean_dxdz.SetLineColor(ROOT.kBlue)
h_dataafter_mean_dydz.SetLineColor(ROOT.kBlack)
h_databefore_mean_dydz.SetFillColor(ROOT.kRed)
h_mcafter_mean_dydz.SetLineStyle(3)
h_mcafter_mean_dydz.SetLineColor(ROOT.kGreen+2)
h_millepede_mean_dydz.SetLineStyle(2)
h_millepede_mean_dydz.SetLineColor(ROOT.kBlue)

tlegend = ROOT.TLegend(0.45, 0.8, 0.98, 0.98)
tlegend.SetBorderSize(1)
tlegend.SetFillColor(ROOT.kWhite)
tlegend.AddEntry(h_dataafter_mean_x, "Reference-Target alignment", "l")
tlegend.AddEntry(h_millepede_mean_x, "Millepede alignment", "l")
tlegend.AddEntry(h_mcafter_mean_x, "aligned Monte Carlo (R-T)", "l")
tlegend.AddEntry(h_databefore_mean_x, "unaligned data", "f")
tlegend.SetTextSize(0.04)

h_mcafter_mean_x.SetYTitle("Chambers / %g mm" % (-2.*h_mcafter_mean_x.GetBinLowEdge(1)/h_mcafter_mean_x.GetNbinsX()))
h_mcafter_mean_x.GetYaxis().CenterTitle()
h_mcafter_mean_x.GetYaxis().SetTitleOffset(1.3)
h_mcafter_mean_x.SetXTitle("mean(#Deltax) (mm)")
h_mcafter_mean_x.GetXaxis().CenterTitle()
h_mcafter_mean_x.Draw()
h_databefore_mean_x.Draw("same")
h_millepede_mean_x.Draw("same")
h_dataafter_mean_x.Draw("same")
c1.SaveAs("finalresiduals_mean_x.pdf")

h_mcafter_mean_y.SetYTitle("Chambers / %g mm" % (-2.*h_mcafter_mean_y.GetBinLowEdge(1)/h_mcafter_mean_y.GetNbinsX()))
h_mcafter_mean_y.GetYaxis().CenterTitle()
h_mcafter_mean_y.GetYaxis().SetTitleOffset(1.3)
h_mcafter_mean_y.SetXTitle("mean(#Deltay) (mm)")
h_mcafter_mean_y.GetXaxis().CenterTitle()
h_mcafter_mean_y.Draw()
h_databefore_mean_y.Draw("same")
h_millepede_mean_y.Draw("same")
h_dataafter_mean_y.Draw("same")
c1.SaveAs("finalresiduals_mean_y.pdf")

h_dataafter_mean_dxdz.SetYTitle("Chambers / %g mrad" % (-2.*h_dataafter_mean_dxdz.GetBinLowEdge(1)/h_dataafter_mean_dxdz.GetNbinsX()))
h_dataafter_mean_dxdz.GetYaxis().CenterTitle()
h_dataafter_mean_dxdz.GetYaxis().SetTitleOffset(1.3)
h_dataafter_mean_dxdz.SetXTitle("mean(#Deltadx/dz) (mrad)")
h_dataafter_mean_dxdz.GetXaxis().CenterTitle()
h_dataafter_mean_dxdz.SetAxisRange(0, 85, "Y")
h_dataafter_mean_dxdz.Draw()
h_databefore_mean_dxdz.Draw("same")
h_millepede_mean_dxdz.Draw("same")
h_mcafter_mean_dxdz.Draw("same")
tlegend.Draw()
c1.SaveAs("finalresiduals_mean_dxdz.pdf")

h_mcafter_mean_dydz.SetYTitle("Chambers / %g mrad" % (-2.*h_mcafter_mean_dydz.GetBinLowEdge(1)/h_mcafter_mean_dydz.GetNbinsX()))
h_mcafter_mean_dydz.GetYaxis().CenterTitle()
h_mcafter_mean_dydz.GetYaxis().SetTitleOffset(1.3)
h_mcafter_mean_dydz.SetXTitle("mean(#Deltady/dz) (mrad)")
h_mcafter_mean_dydz.GetXaxis().CenterTitle()
h_mcafter_mean_dydz.Draw()
h_databefore_mean_dydz.Draw("same")
h_millepede_mean_dydz.Draw("same")
h_dataafter_mean_dydz.Draw("same")
c1.SaveAs("finalresiduals_mean_dydz.pdf")

##################################

h_databefore_peak_x = ROOT.TH1F("databefore_peak_x", "", 50, -3, 3)
h_dataafter_peak_x = ROOT.TH1F("dataafter_peak_x", "", 50, -3, 3)
h_mcafter_peak_x = ROOT.TH1F("mcafter_peak_x", "", 50, -3, 3)
h_millepede_peak_x = ROOT.TH1F("millepede_peak_x", "", 50, -3, 3)
h_databefore_peak_y = ROOT.TH1F("databefore_peak_y", "", 50, -3, 3)
h_dataafter_peak_y = ROOT.TH1F("dataafter_peak_y", "", 50, -3, 3)
h_mcafter_peak_y = ROOT.TH1F("mcafter_peak_y", "", 50, -3, 3)
h_millepede_peak_y = ROOT.TH1F("millepede_peak_y", "", 50, -3, 3)
h_databefore_peak_dxdz = ROOT.TH1F("databefore_peak_dxdz", "", 50, -3, 3)
h_dataafter_peak_dxdz = ROOT.TH1F("dataafter_peak_dxdz", "", 50, -3, 3)
h_mcafter_peak_dxdz = ROOT.TH1F("mcafter_peak_dxdz", "", 50, -3, 3)
h_millepede_peak_dxdz = ROOT.TH1F("millepede_peak_dxdz", "", 50, -3, 3)
h_databefore_peak_dydz = ROOT.TH1F("databefore_peak_dydz", "", 50, -5, 5)
h_dataafter_peak_dydz = ROOT.TH1F("dataafter_peak_dydz", "", 50, -5, 5)
h_mcafter_peak_dydz = ROOT.TH1F("mcafter_peak_dydz", "", 50, -5, 5)
h_millepede_peak_dydz = ROOT.TH1F("millepede_peak_dydz", "", 50, -5, 5)

for x in databefore_peak_x: h_databefore_peak_x.Fill(x)
for x in dataafter_peak_x: h_dataafter_peak_x.Fill(x)
for x in mcafter_peak_x: h_mcafter_peak_x.Fill(x)
for x in millepede_peak_x: h_millepede_peak_x.Fill(x)
for x in databefore_peak_y: h_databefore_peak_y.Fill(x)
for x in dataafter_peak_y: h_dataafter_peak_y.Fill(x)
for x in mcafter_peak_y: h_mcafter_peak_y.Fill(x)
for x in millepede_peak_y: h_millepede_peak_y.Fill(x)
for x in databefore_peak_dxdz: h_databefore_peak_dxdz.Fill(x)
for x in dataafter_peak_dxdz: h_dataafter_peak_dxdz.Fill(x)
for x in mcafter_peak_dxdz: h_mcafter_peak_dxdz.Fill(x)
for x in millepede_peak_dxdz: h_millepede_peak_dxdz.Fill(x)
for x in databefore_peak_dydz: h_databefore_peak_dydz.Fill(x)
for x in dataafter_peak_dydz: h_dataafter_peak_dydz.Fill(x)
for x in mcafter_peak_dydz: h_mcafter_peak_dydz.Fill(x)
for x in millepede_peak_dydz: h_millepede_peak_dydz.Fill(x)

h_dataafter_peak_x.SetLineColor(ROOT.kBlack)
h_databefore_peak_x.SetFillColor(ROOT.kRed)
h_mcafter_peak_x.SetLineStyle(3)
h_mcafter_peak_x.SetLineColor(ROOT.kGreen+2)
h_millepede_peak_x.SetLineStyle(2)
h_millepede_peak_x.SetLineColor(ROOT.kBlue)
h_dataafter_peak_y.SetLineColor(ROOT.kBlack)
h_databefore_peak_y.SetFillColor(ROOT.kRed)
h_mcafter_peak_y.SetLineStyle(3)
h_mcafter_peak_y.SetLineColor(ROOT.kGreen+2)
h_millepede_peak_y.SetLineStyle(2)
h_millepede_peak_y.SetLineColor(ROOT.kBlue)
h_dataafter_peak_dxdz.SetLineColor(ROOT.kBlack)
h_databefore_peak_dxdz.SetFillColor(ROOT.kRed)
h_mcafter_peak_dxdz.SetLineStyle(3)
h_mcafter_peak_dxdz.SetLineColor(ROOT.kGreen+2)
h_millepede_peak_dxdz.SetLineStyle(2)
h_millepede_peak_dxdz.SetLineColor(ROOT.kBlue)
h_dataafter_peak_dydz.SetLineColor(ROOT.kBlack)
h_databefore_peak_dydz.SetFillColor(ROOT.kRed)
h_mcafter_peak_dydz.SetLineStyle(3)
h_mcafter_peak_dydz.SetLineColor(ROOT.kGreen+2)
h_millepede_peak_dydz.SetLineStyle(2)
h_millepede_peak_dydz.SetLineColor(ROOT.kBlue)

tlegend = ROOT.TLegend(0.45, 0.8, 0.98, 0.98)
tlegend.SetBorderSize(1)
tlegend.SetFillColor(ROOT.kWhite)
tlegend.AddEntry(h_dataafter_peak_x, "Reference-Target alignment", "l")
tlegend.AddEntry(h_millepede_peak_x, "Millepede alignment", "l")
tlegend.AddEntry(h_mcafter_peak_x, "aligned Monte Carlo (R-T)", "l")
tlegend.AddEntry(h_databefore_peak_x, "unaligned data", "f")
tlegend.SetTextSize(0.04)

h_mcafter_peak_x.SetYTitle("Chambers / %g mm" % (-2.*h_mcafter_peak_x.GetBinLowEdge(1)/h_mcafter_peak_x.GetNbinsX()))
h_mcafter_peak_x.GetYaxis().CenterTitle()
h_mcafter_peak_x.GetYaxis().SetTitleOffset(1.3)
h_mcafter_peak_x.SetXTitle("peak(#Deltax) (mm)")
h_mcafter_peak_x.GetXaxis().CenterTitle()
h_mcafter_peak_x.Draw()
h_databefore_peak_x.Draw("same")
h_millepede_peak_x.Draw("same")
h_dataafter_peak_x.Draw("same")
c1.SaveAs("finalresiduals_peak_x.pdf")

h_mcafter_peak_y.SetYTitle("Chambers / %g mm" % (-2.*h_mcafter_peak_y.GetBinLowEdge(1)/h_mcafter_peak_y.GetNbinsX()))
h_mcafter_peak_y.GetYaxis().CenterTitle()
h_mcafter_peak_y.GetYaxis().SetTitleOffset(1.3)
h_mcafter_peak_y.SetXTitle("peak(#Deltay) (mm)")
h_mcafter_peak_y.GetXaxis().CenterTitle()
h_mcafter_peak_y.Draw()
h_databefore_peak_y.Draw("same")
h_millepede_peak_y.Draw("same")
h_dataafter_peak_y.Draw("same")
c1.SaveAs("finalresiduals_peak_y.pdf")

h_mcafter_peak_dxdz.SetYTitle("Chambers / %g mrad" % (-2.*h_mcafter_peak_dxdz.GetBinLowEdge(1)/h_mcafter_peak_dxdz.GetNbinsX()))
h_mcafter_peak_dxdz.GetYaxis().CenterTitle()
h_mcafter_peak_dxdz.GetYaxis().SetTitleOffset(1.3)
h_mcafter_peak_dxdz.SetXTitle("peak(#Deltadx/dz) (mrad)")
h_mcafter_peak_dxdz.GetXaxis().CenterTitle()
h_mcafter_peak_dxdz.SetAxisRange(0, 90, "Y")
h_mcafter_peak_dxdz.Draw()
h_databefore_peak_dxdz.Draw("same")
h_millepede_peak_dxdz.Draw("same")
h_dataafter_peak_dxdz.Draw("same")
tlegend.Draw()
c1.SaveAs("finalresiduals_peak_dxdz.pdf")

h_mcafter_peak_dydz.SetYTitle("Chambers / %g mrad" % (-2.*h_mcafter_peak_dydz.GetBinLowEdge(1)/h_mcafter_peak_dydz.GetNbinsX()))
h_mcafter_peak_dydz.GetYaxis().CenterTitle()
h_mcafter_peak_dydz.GetYaxis().SetTitleOffset(1.3)
h_mcafter_peak_dydz.SetXTitle("peak(#Deltady/dz) (mrad)")
h_mcafter_peak_dydz.GetXaxis().CenterTitle()
h_mcafter_peak_dydz.Draw()
h_databefore_peak_dydz.Draw("same")
h_millepede_peak_dydz.Draw("same")
h_dataafter_peak_dydz.Draw("same")
c1.SaveAs("finalresiduals_peak_dydz.pdf")

##############################################

# h_databefore_peak_x = ROOT.TH1F("databefore_peak_x", "", 70, -4, 3)
# h_dataafter_peak_x = ROOT.TH1F("dataafter_peak_x", "", 70, -4, 3)
# h_mcafter_peak_x = ROOT.TH1F("mcafter_peak_x", "", 70, -4, 3)
# h_databefore_peak_y = ROOT.TH1F("databefore_peak_y", "", 70, -4, 3)
# h_dataafter_peak_y = ROOT.TH1F("dataafter_peak_y", "", 70, -4, 3)
# h_mcafter_peak_y = ROOT.TH1F("mcafter_peak_y", "", 70, -4, 3)
# h_databefore_peak_dxdz = ROOT.TH1F("databefore_peak_dxdz", "", 70, -4, 3)
# h_dataafter_peak_dxdz = ROOT.TH1F("dataafter_peak_dxdz", "", 70, -4, 3)
# h_mcafter_peak_dxdz = ROOT.TH1F("mcafter_peak_dxdz", "", 70, -4, 3)
# h_databefore_peak_dydz = ROOT.TH1F("databefore_peak_dydz", "", 70, -4, 3)
# h_dataafter_peak_dydz = ROOT.TH1F("dataafter_peak_dydz", "", 70, -4, 3)
# h_mcafter_peak_dydz = ROOT.TH1F("mcafter_peak_dydz", "", 70, -4, 3)

# for x in databefore_peak_x: h_databefore_peak_x.Fill(log10(abs(x)))
# for x in dataafter_peak_x: h_dataafter_peak_x.Fill(log10(abs(x)))
# for x in mcafter_peak_x: h_mcafter_peak_x.Fill(log10(abs(x)))
# for x in databefore_peak_y: h_databefore_peak_y.Fill(log10(abs(x)))
# for x in dataafter_peak_y: h_dataafter_peak_y.Fill(log10(abs(x)))
# for x in mcafter_peak_y: h_mcafter_peak_y.Fill(log10(abs(x)))
# for x in databefore_peak_dxdz: h_databefore_peak_dxdz.Fill(log10(abs(x)))
# for x in dataafter_peak_dxdz: h_dataafter_peak_dxdz.Fill(log10(abs(x)))
# for x in mcafter_peak_dxdz: h_mcafter_peak_dxdz.Fill(log10(abs(x)))
# for x in databefore_peak_dydz: h_databefore_peak_dydz.Fill(log10(abs(x)))
# for x in dataafter_peak_dydz: h_dataafter_peak_dydz.Fill(log10(abs(x)))
# for x in mcafter_peak_dydz: h_mcafter_peak_dydz.Fill(log10(abs(x)))

# h_dataafter_peak_x.SetLineColor(ROOT.kBlack)
# h_databefore_peak_x.SetFillColor(ROOT.kRed)
# h_mcafter_peak_x.SetLineStyle(3)
# h_mcafter_peak_x.SetLineColor(ROOT.kGreen+2)
# h_dataafter_peak_y.SetLineColor(ROOT.kBlack)
# h_databefore_peak_y.SetFillColor(ROOT.kRed)
# h_mcafter_peak_y.SetLineStyle(3)
# h_mcafter_peak_y.SetLineColor(ROOT.kGreen+2)
# h_dataafter_peak_dxdz.SetLineColor(ROOT.kBlack)
# h_databefore_peak_dxdz.SetFillColor(ROOT.kRed)
# h_mcafter_peak_dxdz.SetLineStyle(3)
# h_mcafter_peak_dxdz.SetLineColor(ROOT.kGreen+2)
# h_dataafter_peak_dydz.SetLineColor(ROOT.kBlack)
# h_databefore_peak_dydz.SetFillColor(ROOT.kRed)
# h_mcafter_peak_dydz.SetLineStyle(3)
# h_mcafter_peak_dydz.SetLineColor(ROOT.kGreen+2)

# h_dataafter_peak_x.SetXTitle("|peak(#Deltax)| (log scale)")
# h_dataafter_peak_x.GetXaxis().CenterTitle()
# h_dataafter_peak_x.GetXaxis().SetBinLabel(1, "0.1 #mum")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(11, "#mum")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(21, "10 #mum")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(31, "100 #mum")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(41, "mm")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(51, "cm")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(61, "10 cm")
# h_dataafter_peak_x.GetXaxis().SetBinLabel(70, "100 cm")
# h_dataafter_peak_x.GetXaxis().SetTitleOffset(1.5)
# h_dataafter_peak_x.GetXaxis().SetTickLength(0.01)
# h_dataafter_peak_x.SetYTitle("Chambers per bin")
# h_dataafter_peak_x.GetYaxis().CenterTitle()
# h_dataafter_peak_x.GetYaxis().SetTitleOffset(1.3)
# h_dataafter_peak_x.SetAxisRange(0, 20, "Y")
# h_dataafter_peak_x.Draw()
# h_databefore_peak_x.Draw("same")
# h_mcafter_peak_x.Draw("same")

# h_dataafter_peak_y.SetXTitle("|peak(#Deltay)| (log scale)")
# h_dataafter_peak_y.GetXaxis().CenterTitle()
# h_dataafter_peak_y.GetXaxis().SetBinLabel(1, "0.1 #mum")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(11, "#mum")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(21, "10 #mum")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(31, "100 #mum")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(41, "mm")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(51, "cm")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(61, "10 cm")
# h_dataafter_peak_y.GetXaxis().SetBinLabel(70, "100 cm")
# h_dataafter_peak_y.GetXaxis().SetTitleOffset(1.5)
# h_dataafter_peak_y.GetXaxis().SetTickLength(0.01)
# h_dataafter_peak_y.SetYTitle("Chambers per bin")
# h_dataafter_peak_y.GetYaxis().CenterTitle()
# h_dataafter_peak_y.GetYaxis().SetTitleOffset(1.3)
# h_dataafter_peak_y.SetAxisRange(0, 15, "Y")
# h_dataafter_peak_y.Draw()
# h_databefore_peak_y.Draw("same")
# h_mcafter_peak_y.Draw("same")

# h_dataafter_peak_dxdz.SetXTitle("|peak(#Deltadx/dz)| (log scale)")
# h_dataafter_peak_dxdz.GetXaxis().CenterTitle()
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(1, "0.1 #murad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(11, "#murad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(21, "10 #murad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(31, "100 #murad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(41, "mrad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(51, "10 mrad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(61, "100 mrad")
# h_dataafter_peak_dxdz.GetXaxis().SetBinLabel(70, "rad")
# h_dataafter_peak_dxdz.GetXaxis().SetTitleOffset(1.7)
# h_dataafter_peak_dxdz.GetXaxis().SetTickLength(0.01)
# h_dataafter_peak_dxdz.SetYTitle("Chambers per bin")
# h_dataafter_peak_dxdz.GetYaxis().CenterTitle()
# h_dataafter_peak_dxdz.GetYaxis().SetTitleOffset(1.3)
# h_dataafter_peak_dxdz.SetAxisRange(0, 20, "Y")
# h_dataafter_peak_dxdz.Draw()
# h_databefore_peak_dxdz.Draw("same")
# h_mcafter_peak_dxdz.Draw("same")

# h_dataafter_peak_dydz.SetXTitle("|peak(#Deltady/dz)| (log scale)")
# h_dataafter_peak_dydz.GetXaxis().CenterTitle()
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(1, "0.1 #murad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(11, "#murad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(21, "10 #murad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(31, "100 #murad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(41, "mrad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(51, "10 mrad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(61, "100 mrad")
# h_dataafter_peak_dydz.GetXaxis().SetBinLabel(70, "rad")
# h_dataafter_peak_dydz.GetXaxis().SetTitleOffset(1.7)
# h_dataafter_peak_dydz.GetXaxis().SetTickLength(0.01)
# h_dataafter_peak_dydz.SetYTitle("Chambers per bin")
# h_dataafter_peak_dydz.GetYaxis().CenterTitle()
# h_dataafter_peak_dydz.GetYaxis().SetTitleOffset(1.3)
# h_dataafter_peak_dydz.SetAxisRange(0, 15, "Y")
# h_dataafter_peak_dydz.Draw()
# h_databefore_peak_dydz.Draw("same")
# h_mcafter_peak_dydz.Draw("same")

##########################

h_databefore_sigma_x = ROOT.TH1F("databefore_sigma_x", "", 50, 0, 10)
h_dataafter_sigma_x = ROOT.TH1F("dataafter_sigma_x", "", 50, 0, 10)
h_mcafter_sigma_x = ROOT.TH1F("mcafter_sigma_x", "", 50, 0, 10)
h_millepede_sigma_x = ROOT.TH1F("millepede_sigma_x", "", 50, 0, 10)
h_databefore_sigma_y = ROOT.TH1F("databefore_sigma_y", "", 50, 0, 15)
h_dataafter_sigma_y = ROOT.TH1F("dataafter_sigma_y", "", 50, 0, 15)
h_mcafter_sigma_y = ROOT.TH1F("mcafter_sigma_y", "", 50, 0, 15)
h_millepede_sigma_y = ROOT.TH1F("millepede_sigma_y", "", 50, 0, 15)
h_databefore_sigma_dxdz = ROOT.TH1F("databefore_sigma_dxdz", "", 50, 0, 0)
h_dataafter_sigma_dxdz = ROOT.TH1F("dataafter_sigma_dxdz", "", 50, 0, 5)
h_mcafter_sigma_dxdz = ROOT.TH1F("mcafter_sigma_dxdz", "", 50, 0, 5)
h_millepede_sigma_dxdz = ROOT.TH1F("millepede_sigma_dxdz", "", 50, 0, 5)
h_databefore_sigma_dydz = ROOT.TH1F("databefore_sigma_dydz", "", 50, 0, 30)
h_dataafter_sigma_dydz = ROOT.TH1F("dataafter_sigma_dydz", "", 50, 0, 30)
h_mcafter_sigma_dydz = ROOT.TH1F("mcafter_sigma_dydz", "", 50, 0, 30)
h_millepede_sigma_dydz = ROOT.TH1F("millepede_sigma_dydz", "", 50, 0, 30)

for x in databefore_sigma_x: h_databefore_sigma_x.Fill(x)
for x in dataafter_sigma_x: h_dataafter_sigma_x.Fill(x)
for x in mcafter_sigma_x: h_mcafter_sigma_x.Fill(x)
for x in millepede_sigma_x: h_millepede_sigma_x.Fill(x)
for x in databefore_sigma_y: h_databefore_sigma_y.Fill(x)
for x in dataafter_sigma_y: h_dataafter_sigma_y.Fill(x)
for x in mcafter_sigma_y: h_mcafter_sigma_y.Fill(x)
for x in millepede_sigma_y: h_millepede_sigma_y.Fill(x)
for x in databefore_sigma_dxdz: h_databefore_sigma_dxdz.Fill(x)
for x in dataafter_sigma_dxdz: h_dataafter_sigma_dxdz.Fill(x)
for x in mcafter_sigma_dxdz: h_mcafter_sigma_dxdz.Fill(x)
for x in millepede_sigma_dxdz: h_millepede_sigma_dxdz.Fill(x)
for x in databefore_sigma_dydz: h_databefore_sigma_dydz.Fill(x)
for x in dataafter_sigma_dydz: h_dataafter_sigma_dydz.Fill(x)
for x in mcafter_sigma_dydz: h_mcafter_sigma_dydz.Fill(x)
for x in millepede_sigma_dydz: h_millepede_sigma_dydz.Fill(x)

h_dataafter_sigma_x.SetLineColor(ROOT.kBlack)
h_databefore_sigma_x.SetFillColor(ROOT.kRed)
h_mcafter_sigma_x.SetLineStyle(3)
h_mcafter_sigma_x.SetLineColor(ROOT.kGreen+2)
h_millepede_sigma_x.SetLineStyle(2)
h_millepede_sigma_x.SetLineColor(ROOT.kBlue)
h_dataafter_sigma_y.SetLineColor(ROOT.kBlack)
h_databefore_sigma_y.SetFillColor(ROOT.kRed)
h_mcafter_sigma_y.SetLineStyle(3)
h_mcafter_sigma_y.SetLineColor(ROOT.kGreen+2)
h_millepede_sigma_y.SetLineStyle(2)
h_millepede_sigma_y.SetLineColor(ROOT.kBlue)
h_dataafter_sigma_dxdz.SetLineColor(ROOT.kBlack)
h_databefore_sigma_dxdz.SetFillColor(ROOT.kRed)
h_mcafter_sigma_dxdz.SetLineStyle(3)
h_mcafter_sigma_dxdz.SetLineColor(ROOT.kGreen+2)
h_millepede_sigma_dxdz.SetLineStyle(2)
h_millepede_sigma_dxdz.SetLineColor(ROOT.kBlue)
h_dataafter_sigma_dydz.SetLineColor(ROOT.kBlack)
h_databefore_sigma_dydz.SetFillColor(ROOT.kRed)
h_mcafter_sigma_dydz.SetLineStyle(3)
h_mcafter_sigma_dydz.SetLineColor(ROOT.kGreen+2)
h_millepede_sigma_dydz.SetLineStyle(2)
h_millepede_sigma_dydz.SetLineColor(ROOT.kBlue)

tlegend = ROOT.TLegend(0.3, 0.8, 0.98, 0.98)
tlegend.SetBorderSize(1)
tlegend.SetFillColor(ROOT.kWhite)
tlegend.AddEntry(h_dataafter_sigma_x, "Reference-Target alignment", "l")
tlegend.AddEntry(h_millepede_sigma_x, "Millepede alignment", "l")
tlegend.AddEntry(h_mcafter_sigma_x, "aligned Monte Carlo (R-T)", "l")
tlegend.AddEntry(h_databefore_sigma_x, "unaligned data", "f")
tlegend.SetTextSize(0.04)

h_mcafter_sigma_x.SetYTitle("Chambers / %g mm" % (10./h_mcafter_sigma_x.GetNbinsX()))
h_mcafter_sigma_x.GetYaxis().CenterTitle()
h_mcafter_sigma_x.GetYaxis().SetTitleOffset(1.3)
h_mcafter_sigma_x.SetXTitle("sigma(#Deltax) (mm)")
h_mcafter_sigma_x.GetXaxis().CenterTitle()
h_mcafter_sigma_x.Draw()
h_databefore_sigma_x.Draw("same")
h_millepede_sigma_x.Draw("same")
h_dataafter_sigma_x.Draw("same")
c1.SaveAs("finalresiduals_sigma_x.pdf")

h_dataafter_sigma_y.SetYTitle("Chambers / %g mm" % (15./h_dataafter_sigma_y.GetNbinsX()))
h_dataafter_sigma_y.GetYaxis().CenterTitle()
h_dataafter_sigma_y.GetYaxis().SetTitleOffset(1.3)
h_dataafter_sigma_y.SetXTitle("sigma(#Deltay) (mm)")
h_dataafter_sigma_y.GetXaxis().CenterTitle()
h_dataafter_sigma_y.Draw()
h_databefore_sigma_y.Draw("same")
h_millepede_sigma_y.Draw("same")
h_mcafter_sigma_y.Draw("same")
c1.SaveAs("finalresiduals_sigma_y.pdf")

h_millepede_sigma_dxdz.SetYTitle("Chambers / %g mrad" % (5./h_millepede_sigma_dxdz.GetNbinsX()))
h_millepede_sigma_dxdz.GetYaxis().CenterTitle()
h_millepede_sigma_dxdz.GetYaxis().SetTitleOffset(1.3)
h_millepede_sigma_dxdz.SetXTitle("sigma(#Deltadx/dz) (mrad)")
h_millepede_sigma_dxdz.GetXaxis().CenterTitle()
h_millepede_sigma_dxdz.Draw()
h_databefore_sigma_dxdz.Draw("same")
h_dataafter_sigma_dxdz.Draw("same")
h_mcafter_sigma_dxdz.Draw("same")
c1.SaveAs("finalresiduals_sigma_dxdz.pdf")

h_mcafter_sigma_dydz.SetYTitle("Chambers / %g mrad" % (30./h_mcafter_sigma_dydz.GetNbinsX()))
h_mcafter_sigma_dydz.GetYaxis().CenterTitle()
h_mcafter_sigma_dydz.GetYaxis().SetTitleOffset(1.3)
h_mcafter_sigma_dydz.SetXTitle("sigma(#Deltady/dz) (mrad)")
h_mcafter_sigma_dydz.GetXaxis().CenterTitle()
h_mcafter_sigma_dydz.SetAxisRange(0, 25, "Y")
h_mcafter_sigma_dydz.Draw()
h_databefore_sigma_dydz.Draw("same")
h_millepede_sigma_dydz.Draw("same")
h_dataafter_sigma_dydz.Draw("same")
tlegend.Draw()
c1.SaveAs("finalresiduals_sigma_dydz.pdf")

##########################################################################

for h1, h2, h3 in (h_databefore_mean_x, h_databefore_peak_x, h_databefore_sigma_x), (h_databefore_mean_y, h_databefore_peak_y, h_databefore_sigma_y), (h_databefore_mean_dxdz, h_databefore_peak_dxdz, h_databefore_sigma_dxdz), (h_databefore_mean_dydz, h_databefore_peak_dydz, h_databefore_sigma_dydz):
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h1.GetRMS(), h2.GetRMS(), h3.GetMean())

for h1, h2, h3 in (h_dataafter_mean_x, h_dataafter_peak_x, h_dataafter_sigma_x), (h_dataafter_mean_y, h_dataafter_peak_y, h_dataafter_sigma_y), (h_dataafter_mean_dxdz, h_dataafter_peak_dxdz, h_dataafter_sigma_dxdz), (h_dataafter_mean_dydz, h_dataafter_peak_dydz, h_dataafter_sigma_dydz):
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h1.GetRMS(), h2.GetRMS(), h3.GetMean())

for h1, h2, h3 in (h_millepede_mean_x, h_millepede_peak_x, h_millepede_sigma_x), (h_millepede_mean_y, h_millepede_peak_y, h_millepede_sigma_y), (h_millepede_mean_dxdz, h_millepede_peak_dxdz, h_millepede_sigma_dxdz), (h_millepede_mean_dydz, h_millepede_peak_dydz, h_millepede_sigma_dydz):
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h1.GetRMS(), h2.GetRMS(), h3.GetMean())

for h1, h2, h3 in (h_mcafter_mean_x, h_mcafter_peak_x, h_mcafter_sigma_x), (h_mcafter_mean_y, h_mcafter_peak_y, h_mcafter_sigma_y), (h_mcafter_mean_dxdz, h_mcafter_peak_dxdz, h_mcafter_sigma_dxdz), (h_mcafter_mean_dydz, h_mcafter_peak_dydz, h_mcafter_sigma_dydz):
    print "& %4.2f & %4.2f & %4.2f \\\\" % (h1.GetRMS(), h2.GetRMS(), h3.GetMean())





##############################################


#    c1.SaveAs("tmppoly_%s.pdf" % name)

# bellcurves("DTexample")
# polynomials("DTexample")
# bellcurves("CSCexample")
# polynomials("CSCexample")

# bellcurves("MBwhCst1sec10", False)
# polynomials("MBwhCst1sec10", False)

# c1.SaveAs("exampleMC_wh0st1sec10_bellbefore.pdf")
# c1.SaveAs("exampleMC_wh0st1sec10_bellafter.pdf")
# c1.SaveAs("exampleMC_wh0st1sec10_polybefore.pdf")
# c1.SaveAs("exampleMC_wh0st1sec10_polyafter.pdf")
# c1.SaveAs("exampleData_wh0st1sec10_bellbefore.pdf")
# c1.SaveAs("exampleData_wh0st1sec10_bellafter.pdf")
# c1.SaveAs("exampleData_wh0st1sec10_polybefore.pdf")
# c1.SaveAs("exampleData_wh0st1sec10_polyafter.pdf")

# c1.SaveAs("datafit_wh0st1sec10_lowp.pdf")
# c1.SaveAs("datafit_wh0st1sec10_highp.pdf")



# bellcurves("MBwhDst4sec04")
# polynomials("MBwhDst4sec04")
# bellcurves("MBwhDst4sec09")
# polynomials("MBwhDst4sec09")

# bellcurves("MBwhDst4sec04", False)
# polynomials("MBwhDst4sec04", False)
# bellcurves("MBwhDst4sec09", False)
# polynomials("MBwhDst4sec09", False)


# bellcurves("MEp21_06", suppressblue=True)
# c1.SaveAs("mcfit_cscexample_bellafter.pdf")

# polynomials("MEp21_06", suppressblue=True)
# c1.SaveAs("mcfit_cscexample_polyafter.pdf")




# for r in reports:
#     if r.status != "PASS":
#         print r.status, r.postal_address

# fits = []
# for r in reports:
#     if r.status == "PASS": # and abs(r.deltax.value)*10. < 0.1:
#         fits.append(r.name)
# fits.sort()
# for f in fits:
# #     print "bellcurves(\"%s\", False)" % f
#     print "polynomials(\"%s\", False)" % f
# #     print "sawtooth(\"%s\")" % f

# sawtooths = {}
# sawtoothserr = {}
# def sawtooth(name):
#     global sawtooths
#     saw = tfile.Get("%s/%sPos_dxdz_trackdxdz" % (plotDirectory, name))
#     if saw is None:
#         saw = tfile.Get("%s/%sPos_resslope_trackdxdz" % (plotDirectory, name))
#     saw = saw.Clone()
#     for i in xrange(1, saw.GetNbinsX()+1):
#         if saw.GetBinError(i) < 0.01:
#             saw.SetBinError(i, 1000.)
#     saw.Fit("pol1")
#     sawtooths[name] = saw.GetFunction("pol1").GetParameter(1)
#     sawtoothserr[name] = saw.GetFunction("pol1").GetParError(1)

# c1.Clear()

# sawtooth("MBwhAst2sec05")
# sawtooth("MBwhAst3sec02")
# sawtooth("MBwhAst3sec03")
# sawtooth("MBwhAst3sec08")
# sawtooth("MBwhAst3sec09")
# sawtooth("MBwhAst3sec10")
# sawtooth("MBwhAst3sec11")
# sawtooth("MBwhAst4sec02")
# sawtooth("MBwhAst4sec03")
# sawtooth("MBwhAst4sec04")
# sawtooth("MBwhAst4sec05")
# sawtooth("MBwhAst4sec06")
# sawtooth("MBwhAst4sec08")
# sawtooth("MBwhAst4sec09")
# sawtooth("MBwhAst4sec10")
# sawtooth("MBwhAst4sec11")
# sawtooth("MBwhAst4sec12")
# sawtooth("MBwhAst4sec13")
# sawtooth("MBwhAst4sec14")
# sawtooth("MBwhBst1sec02")
# sawtooth("MBwhBst1sec03")
# sawtooth("MBwhBst1sec04")
# sawtooth("MBwhBst1sec05")
# sawtooth("MBwhBst1sec06")
# sawtooth("MBwhBst1sec08")
# sawtooth("MBwhBst1sec09")
# sawtooth("MBwhBst1sec10")
# sawtooth("MBwhBst1sec11")
# sawtooth("MBwhBst2sec02")
# sawtooth("MBwhBst2sec03")
# sawtooth("MBwhBst2sec04")
# sawtooth("MBwhBst2sec05")
# sawtooth("MBwhBst2sec06")
# sawtooth("MBwhBst2sec09")
# sawtooth("MBwhBst2sec10")
# sawtooth("MBwhBst2sec11")
# sawtooth("MBwhBst2sec12")
# sawtooth("MBwhBst3sec02")
# sawtooth("MBwhBst3sec03")
# sawtooth("MBwhBst3sec04")
# sawtooth("MBwhBst3sec05")
# sawtooth("MBwhBst3sec06")
# sawtooth("MBwhBst3sec08")
# sawtooth("MBwhBst3sec09")
# sawtooth("MBwhBst3sec10")
# sawtooth("MBwhBst3sec11")
# sawtooth("MBwhBst3sec12")
# sawtooth("MBwhBst4sec02")
# sawtooth("MBwhBst4sec03")
# sawtooth("MBwhBst4sec04")
# sawtooth("MBwhBst4sec05")
# sawtooth("MBwhBst4sec06")
# sawtooth("MBwhBst4sec08")
# sawtooth("MBwhBst4sec09")
# sawtooth("MBwhBst4sec10")
# sawtooth("MBwhBst4sec11")
# sawtooth("MBwhBst4sec12")
# sawtooth("MBwhBst4sec13")
# sawtooth("MBwhBst4sec14")
# sawtooth("MBwhCst1sec01")
# sawtooth("MBwhCst1sec02")
# sawtooth("MBwhCst1sec03")
# sawtooth("MBwhCst1sec04")
# sawtooth("MBwhCst1sec05")
# sawtooth("MBwhCst1sec06")
# sawtooth("MBwhCst1sec07")
# sawtooth("MBwhCst1sec08")
# sawtooth("MBwhCst1sec09")
# sawtooth("MBwhCst1sec10")
# sawtooth("MBwhCst1sec11")
# sawtooth("MBwhCst1sec12")
# sawtooth("MBwhCst2sec02")
# sawtooth("MBwhCst2sec03")
# sawtooth("MBwhCst2sec04")
# sawtooth("MBwhCst2sec05")
# sawtooth("MBwhCst2sec06")
# sawtooth("MBwhCst2sec08")
# sawtooth("MBwhCst2sec09")
# sawtooth("MBwhCst2sec10")
# sawtooth("MBwhCst2sec11")
# sawtooth("MBwhCst2sec12")
# sawtooth("MBwhCst3sec01")
# sawtooth("MBwhCst3sec02")
# sawtooth("MBwhCst3sec03")
# sawtooth("MBwhCst3sec04")
# sawtooth("MBwhCst3sec05")
# sawtooth("MBwhCst3sec06")
# sawtooth("MBwhCst3sec08")
# sawtooth("MBwhCst3sec09")
# sawtooth("MBwhCst3sec10")
# sawtooth("MBwhCst3sec11")
# sawtooth("MBwhCst3sec12")
# sawtooth("MBwhCst4sec01")
# sawtooth("MBwhCst4sec02")
# sawtooth("MBwhCst4sec03")
# sawtooth("MBwhCst4sec04")
# sawtooth("MBwhCst4sec05")
# sawtooth("MBwhCst4sec06")
# sawtooth("MBwhCst4sec07")
# sawtooth("MBwhCst4sec08")
# sawtooth("MBwhCst4sec09")
# sawtooth("MBwhCst4sec10")
# sawtooth("MBwhCst4sec11")
# sawtooth("MBwhCst4sec12")
# sawtooth("MBwhCst4sec13")
# sawtooth("MBwhCst4sec14")
# sawtooth("MBwhDst1sec02")
# sawtooth("MBwhDst1sec03")
# sawtooth("MBwhDst1sec04")
# sawtooth("MBwhDst1sec05")
# sawtooth("MBwhDst1sec06")
# sawtooth("MBwhDst1sec07")
# sawtooth("MBwhDst1sec08")
# sawtooth("MBwhDst1sec09")
# sawtooth("MBwhDst1sec10")
# sawtooth("MBwhDst1sec11")
# sawtooth("MBwhDst1sec12")
# sawtooth("MBwhDst2sec03")
# sawtooth("MBwhDst2sec04")
# sawtooth("MBwhDst2sec05")
# sawtooth("MBwhDst2sec06")
# sawtooth("MBwhDst2sec08")
# sawtooth("MBwhDst2sec09")
# sawtooth("MBwhDst2sec10")
# sawtooth("MBwhDst2sec11")
# sawtooth("MBwhDst2sec12")
# sawtooth("MBwhDst3sec02")
# sawtooth("MBwhDst3sec03")
# sawtooth("MBwhDst3sec04")
# sawtooth("MBwhDst3sec05")
# sawtooth("MBwhDst3sec06")
# sawtooth("MBwhDst3sec09")
# sawtooth("MBwhDst3sec10")
# sawtooth("MBwhDst3sec11")
# sawtooth("MBwhDst3sec12")
# sawtooth("MBwhDst4sec02")
# sawtooth("MBwhDst4sec03")
# sawtooth("MBwhDst4sec04")
# sawtooth("MBwhDst4sec05")
# sawtooth("MBwhDst4sec06")
# sawtooth("MBwhDst4sec07")
# sawtooth("MBwhDst4sec08")
# sawtooth("MBwhDst4sec09")
# sawtooth("MBwhDst4sec10")
# sawtooth("MBwhDst4sec11")
# sawtooth("MBwhDst4sec12")
# sawtooth("MBwhDst4sec13")
# sawtooth("MBwhDst4sec14")
# sawtooth("MBwhEst2sec04")
# sawtooth("MBwhEst3sec02")
# sawtooth("MBwhEst3sec03")
# sawtooth("MBwhEst3sec04")
# sawtooth("MBwhEst3sec08")
# sawtooth("MBwhEst3sec10")
# sawtooth("MBwhEst3sec11")
# sawtooth("MBwhEst3sec12")
# sawtooth("MBwhEst4sec02")
# sawtooth("MBwhEst4sec04")
# sawtooth("MBwhEst4sec05")
# sawtooth("MBwhEst4sec06")
# sawtooth("MBwhEst4sec07")
# sawtooth("MBwhEst4sec08")
# sawtooth("MBwhEst4sec09")
# sawtooth("MBwhEst4sec10")
# sawtooth("MBwhEst4sec11")
# sawtooth("MBwhEst4sec12")
# sawtooth("MBwhEst4sec13")
# sawtooth("MBwhEst4sec14")


# def drawbarrel(fileName, reports, whattodo, template="template_barrel.svg"):
#     template = file(template)
#     output = file(fileName, "w")
#     for line in template.readlines():
#         outline = line
#         match = re.search("id=\"([A-Za-z0-9]+)\".*fill=\"[A-Za-z0-9]+\"", line)
#         if match is not None:
#             name = match.groups()[0]
#             for r in reports:
#                 if r.name == name:
#                     outline = re.sub("fill=\"[A-Za-z0-9]+\"", "fill=\"%s\"" % whattodo(r), line)
#                     break
#         output.write(outline)
#     output.close()

# def rgb(r, g, b, maximum=1.):
#   return "#%02x%02x%02x" % (max(0, min(r*255./maximum, 255)), max(0, min(g*255./maximum, 255)), max(0, min(b*255./maximum, 255)))

# h2_highpt = ROOT.TH1F("h2_highpt", "", 100, -20, 20)

# def drawsawtooth(r):
#     if r.name not in sawtooths: return "none"
#     if sawtoothserr[r.name] < 1.:
#         h2_highpt.Fill(sawtooths[r.name])
# #    val = (sawtooths[r.name] - -20) / (20 - -20)
#     val = (sawtooths[r.name] - -15) / (15 - -15)
#     return rgb(sin(val*(pi/2.)), 0., cos(val*(pi/2.)))

# drawbarrel("data_sawtooth.svg", reports, drawsawtooth)

# tdrStyle.SetOptFit(0)
# histograms = {}
# for wheel in "B", "C", "D":
#     for station in "1", "2", "3":
#         histograms[wheel + station] = ROOT.TH1F("hst%swh%s" % (station, wheel), "", 12, 0.5, 12.5)
#         histograms[wheel + station].SetAxisRange(-20, 20, "Y")
#         for sector in 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12:
#             if "MBwh%sst%ssec%02d" % (wheel, station, sector) in sawtooths:
#                 histograms[wheel + station].SetBinContent(sector, sawtooths["MBwh%sst%ssec%02d" % (wheel, station, sector)])
#                 histograms[wheel + station].SetBinError(sector, sawtoothserr["MBwh%sst%ssec%02d" % (wheel, station, sector)])
#             else:
#                 histograms[wheel + station].SetBinContent(sector, 2000.)
#                 histograms[wheel + station].SetBinError(sector, 1000.)

# histograms["B1"].SetLineColor(ROOT.kRed);       histograms["B1"].SetMarkerColor(ROOT.kRed)
# histograms["C1"].SetLineColor(ROOT.kYellow+2);  histograms["C1"].SetMarkerColor(ROOT.kYellow+2)
# histograms["D1"].SetLineColor(ROOT.kSpring-7);  histograms["D1"].SetMarkerColor(ROOT.kSpring-7)
# histograms["B2"].SetLineColor(ROOT.kGreen+3);   histograms["B2"].SetMarkerColor(ROOT.kGreen+3)
# histograms["C2"].SetLineColor(ROOT.kCyan+2);    histograms["C2"].SetMarkerColor(ROOT.kCyan+2)
# histograms["D2"].SetLineColor(ROOT.kAzure);     histograms["D2"].SetMarkerColor(ROOT.kAzure)
# histograms["B3"].SetLineColor(ROOT.kBlue+2);    histograms["B3"].SetMarkerColor(ROOT.kBlue+2)
# histograms["C3"].SetLineColor(ROOT.kViolet+2);  histograms["C3"].SetMarkerColor(ROOT.kViolet+2)
# histograms["D3"].SetLineColor(ROOT.kMagenta+1); histograms["D3"].SetMarkerColor(ROOT.kMagenta+1)

# histograms["B1"].SetXTitle("Sector number")
# histograms["B1"].SetYTitle("Degree of sawtooth (mrad/rad)")
# histograms["B1"].GetXaxis().CenterTitle()
# histograms["B1"].GetYaxis().CenterTitle()

# histograms["C1"].SetXTitle("Sector number")
# histograms["C1"].SetYTitle("Degree of sawtooth (mrad/rad)")
# histograms["C1"].GetXaxis().CenterTitle()
# histograms["C1"].GetYaxis().CenterTitle()

# def drawtlegend(wheelB=True, wheelC=True, wheelD=True):
#     tlegend1 = ROOT.TLegend(0.15, 0.75, 0.35, 0.9)
#     tlegend1.SetFillColor(ROOT.kWhite)
#     tlegend1.SetBorderSize(0)
#     if wheelB: tlegend1.AddEntry(histograms["B1"], "wh-1 st1", "p")
#     if wheelC: tlegend1.AddEntry(histograms["C1"], "wh 0 st1", "p")
#     if wheelD: tlegend1.AddEntry(histograms["D1"], "wh+1 st1", "p")
#     tlegend1.Draw()
#     tlegend2 = ROOT.TLegend(0.15+0.15, 0.75, 0.35+0.15, 0.9)
#     tlegend2.SetFillColor(ROOT.kWhite)
#     tlegend2.SetBorderSize(0)
#     if wheelB: tlegend2.AddEntry(histograms["B2"], "wh-1 st2", "p")
#     if wheelC: tlegend2.AddEntry(histograms["C2"], "wh 0 st2", "p")
#     if wheelD: tlegend2.AddEntry(histograms["D2"], "wh+1 st2", "p")
#     tlegend2.Draw()
#     tlegend3 = ROOT.TLegend(0.15+2*0.15, 0.75, 0.35+2*0.15, 0.9)
#     tlegend3.SetFillColor(ROOT.kWhite)
#     tlegend3.SetBorderSize(0)
#     if wheelB: tlegend3.AddEntry(histograms["B3"], "wh-1 st3", "p")
#     if wheelC: tlegend3.AddEntry(histograms["C3"], "wh 0 st3", "p")
#     if wheelD: tlegend3.AddEntry(histograms["D3"], "wh+1 st3", "p")
#     tlegend3.Draw()
#     return tlegend1, tlegend2, tlegend3

# histograms["B1"].Draw("e1")
# histograms["B2"].Draw("e1same")
# histograms["B3"].Draw("e1same")
# histograms["C1"].Draw("e1same")
# histograms["C2"].Draw("e1same")
# histograms["C3"].Draw("e1same")
# histograms["D1"].Draw("e1same")
# histograms["D2"].Draw("e1same")
# histograms["D3"].Draw("e1same")
# tlegend1, tlegend2, tlegend3 = drawtlegend()
# tline = ROOT.TLine(0.5, 0., 12.5, 0.)
# tline.SetLineStyle(2)
# tline.Draw()
# f = ROOT.TF1("f", "-4*sin((x-0.5)/6*3.1415926)", 0.5, 12.5)
# f.SetLineStyle(3)
# f.SetLineColor(ROOT.kBlack)
# f.Draw("same")
# ROOT.gPad.SaveAs("sawtooth_bysector_highp_newinternal_zalign.pdf")

# f = ROOT.TF1("f", "[0]*sin((x-[1])/6*3.1415926)", 0.5, 12.5)
# histograms["B1"].Fit(f)
# histograms["B2"].Fit(f)
# histograms["B3"].Fit(f)
# histograms["C1"].Fit(f)
# histograms["C2"].Fit(f)
# histograms["C3"].Fit(f)
# histograms["D1"].Fit(f)
# histograms["D2"].Fit(f)
# histograms["D3"].Fit(f)
# histograms["B1"].GetFunction("f").SetLineColor(ROOT.kRed)
# histograms["C1"].GetFunction("f").SetLineColor(ROOT.kYellow+2)
# histograms["D1"].GetFunction("f").SetLineColor(ROOT.kSpring-7)
# histograms["B2"].GetFunction("f").SetLineColor(ROOT.kGreen+3)
# histograms["C2"].GetFunction("f").SetLineColor(ROOT.kCyan+2)
# histograms["D2"].GetFunction("f").SetLineColor(ROOT.kAzure)
# histograms["B3"].GetFunction("f").SetLineColor(ROOT.kBlue+2)
# histograms["C3"].GetFunction("f").SetLineColor(ROOT.kViolet+2)
# histograms["D3"].GetFunction("f").SetLineColor(ROOT.kMagenta+1)
# histograms["B1"].Draw("e1")
# histograms["B2"].Draw("e1same")
# histograms["B3"].Draw("e1same")
# histograms["C1"].Draw("e1same")
# histograms["C2"].Draw("e1same")
# histograms["C3"].Draw("e1same")
# histograms["D1"].Draw("e1same")
# histograms["D2"].Draw("e1same")
# histograms["D3"].Draw("e1same")
# tlegend1, tlegend2, tlegend3 = drawtlegend()
# tline = ROOT.TLine(0.5, 0., 12.5, 0.)
# tline.SetLineStyle(2)
# tline.Draw()
# ROOT.gPad.SaveAs("sawtooth_bysector_highp_newinternal_zalign_fits.pdf")

# histograms["B1"].Draw("e1")
# histograms["B2"].Draw("e1same")
# histograms["B3"].Draw("e1same")
# tlegend1, tlegend2, tlegend3 = drawtlegend(wheelB=True, wheelC=False, wheelD=False)
# tline = ROOT.TLine(0.5, 0., 12.5, 0.)
# tline.SetLineStyle(2)
# tline.Draw()
# ROOT.gPad.SaveAs("sawtooth_bysector_highp_newinternal_zalign_fits2.pdf")

# histograms["C1"].Draw("e1")
# histograms["C2"].Draw("e1same")
# histograms["C3"].Draw("e1same")
# histograms["D1"].Draw("e1same")
# histograms["D2"].Draw("e1same")
# histograms["D3"].Draw("e1same")
# tlegend1, tlegend2, tlegend3 = drawtlegend(wheelB=False, wheelC=True, wheelD=True)
# tline = ROOT.TLine(0.5, 0., 12.5, 0.)
# tline.SetLineStyle(2)
# tline.Draw()
# ROOT.gPad.SaveAs("sawtooth_bysector_highp_newinternal_zalign_fits3.pdf")




# polynomials("MBwhBst1sec02", False)
# polynomials("MBwhBst1sec03", False)
# polynomials("MBwhBst1sec04", False)
# polynomials("MBwhBst1sec05", False)
# polynomials("MBwhBst1sec06", False)
# polynomials("MBwhBst1sec08", False)
# polynomials("MBwhBst1sec09", False)
# polynomials("MBwhBst1sec10", False)
# polynomials("MBwhBst1sec11", False)
# polynomials("MBwhBst1sec12", False)
# polynomials("MBwhBst2sec02", False)
# polynomials("MBwhBst2sec03", False)
# polynomials("MBwhBst2sec04", False)
# polynomials("MBwhBst2sec05", False)
# polynomials("MBwhBst2sec06", False)
# polynomials("MBwhBst2sec08", False)
# polynomials("MBwhBst2sec09", False)
# polynomials("MBwhBst2sec10", False)
# polynomials("MBwhBst2sec11", False)
# polynomials("MBwhBst2sec12", False)
# polynomials("MBwhBst3sec02", False)
# polynomials("MBwhBst3sec03", False)
# polynomials("MBwhBst3sec04", False)
# polynomials("MBwhBst3sec05", False)
# polynomials("MBwhBst3sec06", False)
# polynomials("MBwhBst3sec08", False)
# polynomials("MBwhBst3sec09", False)
# polynomials("MBwhBst3sec10", False)
# polynomials("MBwhBst3sec11", False)
# polynomials("MBwhBst3sec12", False)
# polynomials("MBwhBst4sec02", False)
# polynomials("MBwhBst4sec03", False)
# polynomials("MBwhBst4sec04", False)
# polynomials("MBwhBst4sec05", False)
# polynomials("MBwhBst4sec06", False)
# polynomials("MBwhBst4sec08", False)
# polynomials("MBwhBst4sec09", False)
# polynomials("MBwhBst4sec10", False)
# polynomials("MBwhBst4sec11", False)
# polynomials("MBwhBst4sec12", False)
# polynomials("MBwhBst4sec13", False)
# polynomials("MBwhBst4sec14", False)
# polynomials("MBwhCst1sec02", False)
# polynomials("MBwhCst1sec03", False)
# polynomials("MBwhCst1sec04", False)
# polynomials("MBwhCst1sec05", False)
# polynomials("MBwhCst1sec06", False)
# polynomials("MBwhCst1sec08", False)
# polynomials("MBwhCst1sec09", False)
# polynomials("MBwhCst1sec10", False)
# polynomials("MBwhCst1sec11", False)
# polynomials("MBwhCst1sec12", False)
# polynomials("MBwhCst2sec02", False)
# polynomials("MBwhCst2sec03", False)
# polynomials("MBwhCst2sec04", False)
# polynomials("MBwhCst2sec05", False)
# polynomials("MBwhCst2sec06", False)
# polynomials("MBwhCst2sec08", False)
# polynomials("MBwhCst2sec09", False)
# polynomials("MBwhCst2sec10", False)
# polynomials("MBwhCst2sec11", False)
# polynomials("MBwhCst2sec12", False)
# polynomials("MBwhCst3sec02", False)
# polynomials("MBwhCst3sec03", False)
# polynomials("MBwhCst3sec04", False)
# polynomials("MBwhCst3sec05", False)
# polynomials("MBwhCst3sec06", False)
# polynomials("MBwhCst3sec08", False)
# polynomials("MBwhCst3sec09", False)
# polynomials("MBwhCst3sec10", False)
# polynomials("MBwhCst3sec11", False)
# polynomials("MBwhCst3sec12", False)
# polynomials("MBwhCst4sec02", False)
# polynomials("MBwhCst4sec03", False)
# polynomials("MBwhCst4sec04", False)
# polynomials("MBwhCst4sec05", False)
# polynomials("MBwhCst4sec06", False)
# polynomials("MBwhCst4sec08", False)
# polynomials("MBwhCst4sec09", False)
# polynomials("MBwhCst4sec10", False)
# polynomials("MBwhCst4sec11", False)
# polynomials("MBwhCst4sec12", False)
# polynomials("MBwhCst4sec13", False)
# polynomials("MBwhCst4sec14", False)
# polynomials("MBwhDst1sec02", False)
# polynomials("MBwhDst1sec03", False)
# polynomials("MBwhDst1sec04", False)
# polynomials("MBwhDst1sec05", False)
# polynomials("MBwhDst1sec06", False)
# polynomials("MBwhDst1sec08", False)
# polynomials("MBwhDst1sec09", False)
# polynomials("MBwhDst1sec10", False)
# polynomials("MBwhDst1sec11", False)
# polynomials("MBwhDst1sec12", False)
# polynomials("MBwhDst2sec02", False)
# polynomials("MBwhDst2sec03", False)
# polynomials("MBwhDst2sec04", False)
# polynomials("MBwhDst2sec05", False)
# polynomials("MBwhDst2sec06", False)
# polynomials("MBwhDst2sec08", False)
# polynomials("MBwhDst2sec09", False)
# polynomials("MBwhDst2sec10", False)
# polynomials("MBwhDst2sec11", False)
# polynomials("MBwhDst2sec12", False)
# polynomials("MBwhDst3sec02", False)
# polynomials("MBwhDst3sec03", False)
# polynomials("MBwhDst3sec04", False)
# polynomials("MBwhDst3sec05", False)
# polynomials("MBwhDst3sec06", False)
# polynomials("MBwhDst3sec08", False)
# polynomials("MBwhDst3sec09", False)
# polynomials("MBwhDst3sec10", False)
# polynomials("MBwhDst3sec11", False)
# polynomials("MBwhDst3sec12", False)
# polynomials("MBwhDst4sec02", False)
# polynomials("MBwhDst4sec03", False)
# polynomials("MBwhDst4sec04", False)
# polynomials("MBwhDst4sec05", False)
# polynomials("MBwhDst4sec06", False)
# polynomials("MBwhDst4sec08", False)
# polynomials("MBwhDst4sec09", False)
# polynomials("MBwhDst4sec10", False)
# polynomials("MBwhDst4sec11", False)
# polynomials("MBwhDst4sec12", False)
# polynomials("MBwhDst4sec13", False)
# polynomials("MBwhDst4sec14", False)

# bellcurves("MBwhBst1sec02", False)
# bellcurves("MBwhBst1sec03", False)
# bellcurves("MBwhBst1sec04", False)
# bellcurves("MBwhBst1sec05", False)
# bellcurves("MBwhBst1sec06", False)
# bellcurves("MBwhBst1sec08", False)
# bellcurves("MBwhBst1sec09", False)
# bellcurves("MBwhBst1sec10", False)
# bellcurves("MBwhBst1sec11", False)
# bellcurves("MBwhBst1sec12", False)
# bellcurves("MBwhBst2sec02", False)
# bellcurves("MBwhBst2sec03", False)
# bellcurves("MBwhBst2sec04", False)
# bellcurves("MBwhBst2sec05", False)
# bellcurves("MBwhBst2sec06", False)
# bellcurves("MBwhBst2sec08", False)
# bellcurves("MBwhBst2sec09", False)
# bellcurves("MBwhBst2sec10", False)
# bellcurves("MBwhBst2sec11", False)
# bellcurves("MBwhBst2sec12", False)
# bellcurves("MBwhBst3sec02", False)
# bellcurves("MBwhBst3sec03", False)
# bellcurves("MBwhBst3sec04", False)
# bellcurves("MBwhBst3sec05", False)
# bellcurves("MBwhBst3sec06", False)
# bellcurves("MBwhBst3sec08", False)
# bellcurves("MBwhBst3sec09", False)
# bellcurves("MBwhBst3sec10", False)
# bellcurves("MBwhBst3sec11", False)
# bellcurves("MBwhBst3sec12", False)
# bellcurves("MBwhBst4sec02", False)
# bellcurves("MBwhBst4sec03", False)
# bellcurves("MBwhBst4sec04", False)
# bellcurves("MBwhBst4sec05", False)
# bellcurves("MBwhBst4sec06", False)
# bellcurves("MBwhBst4sec08", False)
# bellcurves("MBwhBst4sec09", False)
# bellcurves("MBwhBst4sec10", False)
# bellcurves("MBwhBst4sec11", False)
# bellcurves("MBwhBst4sec12", False)
# bellcurves("MBwhBst4sec13", False)
# bellcurves("MBwhBst4sec14", False)
# bellcurves("MBwhCst1sec02", False)
# bellcurves("MBwhCst1sec03", False)
# bellcurves("MBwhCst1sec04", False)
# bellcurves("MBwhCst1sec05", False)
# bellcurves("MBwhCst1sec06", False)
# bellcurves("MBwhCst1sec08", False)
# bellcurves("MBwhCst1sec09", False)
# bellcurves("MBwhCst1sec10", False)
# bellcurves("MBwhCst1sec11", False)
# bellcurves("MBwhCst1sec12", False)
# bellcurves("MBwhCst2sec02", False)
# bellcurves("MBwhCst2sec03", False)
# bellcurves("MBwhCst2sec04", False)
# bellcurves("MBwhCst2sec05", False)
# bellcurves("MBwhCst2sec06", False)
# bellcurves("MBwhCst2sec08", False)
# bellcurves("MBwhCst2sec09", False)
# bellcurves("MBwhCst2sec10", False)
# bellcurves("MBwhCst2sec11", False)
# bellcurves("MBwhCst2sec12", False)
# bellcurves("MBwhCst3sec02", False)
# bellcurves("MBwhCst3sec03", False)
# bellcurves("MBwhCst3sec04", False)
# bellcurves("MBwhCst3sec05", False)
# bellcurves("MBwhCst3sec06", False)
# bellcurves("MBwhCst3sec08", False)
# bellcurves("MBwhCst3sec09", False)
# bellcurves("MBwhCst3sec10", False)
# bellcurves("MBwhCst3sec11", False)
# bellcurves("MBwhCst3sec12", False)
# bellcurves("MBwhCst4sec02", False)
# bellcurves("MBwhCst4sec03", False)
# bellcurves("MBwhCst4sec04", False)
# bellcurves("MBwhCst4sec05", False)
# bellcurves("MBwhCst4sec06", False)
# bellcurves("MBwhCst4sec08", False)
# bellcurves("MBwhCst4sec09", False)
# bellcurves("MBwhCst4sec10", False)
# bellcurves("MBwhCst4sec11", False)
# bellcurves("MBwhCst4sec12", False)
# bellcurves("MBwhCst4sec13", False)
# bellcurves("MBwhCst4sec14", False)
# bellcurves("MBwhDst1sec02", False)
# bellcurves("MBwhDst1sec03", False)
# bellcurves("MBwhDst1sec04", False)
# bellcurves("MBwhDst1sec05", False)
# bellcurves("MBwhDst1sec06", False)
# bellcurves("MBwhDst1sec08", False)
# bellcurves("MBwhDst1sec09", False)
# bellcurves("MBwhDst1sec10", False)
# bellcurves("MBwhDst1sec11", False)
# bellcurves("MBwhDst1sec12", False)
# bellcurves("MBwhDst2sec02", False)
# bellcurves("MBwhDst2sec03", False)
# bellcurves("MBwhDst2sec04", False)
# bellcurves("MBwhDst2sec05", False)
# bellcurves("MBwhDst2sec06", False)
# bellcurves("MBwhDst2sec08", False)
# bellcurves("MBwhDst2sec09", False)
# bellcurves("MBwhDst2sec10", False)
# bellcurves("MBwhDst2sec11", False)
# bellcurves("MBwhDst2sec12", False)
# bellcurves("MBwhDst3sec02", False)
# bellcurves("MBwhDst3sec03", False)
# bellcurves("MBwhDst3sec04", False)
# bellcurves("MBwhDst3sec05", False)
# bellcurves("MBwhDst3sec06", False)
# bellcurves("MBwhDst3sec08", False)
# bellcurves("MBwhDst3sec09", False)
# bellcurves("MBwhDst3sec10", False)
# bellcurves("MBwhDst3sec11", False)
# bellcurves("MBwhDst3sec12", False)
# bellcurves("MBwhDst4sec02", False)
# bellcurves("MBwhDst4sec03", False)
# bellcurves("MBwhDst4sec04", False)
# bellcurves("MBwhDst4sec05", False)
# bellcurves("MBwhDst4sec06", False)
# bellcurves("MBwhDst4sec08", False)
# bellcurves("MBwhDst4sec09", False)
# bellcurves("MBwhDst4sec10", False)
# bellcurves("MBwhDst4sec11", False)
# bellcurves("MBwhDst4sec12", False)
# bellcurves("MBwhDst4sec13", False)
# bellcurves("MBwhDst4sec14", False)
